#!/usr/bin/env python3
"""Extract and clean Chapter I of VSTB Vol 6. No frills."""
import re

SRC = "/home/vthen/work/post-colonial-vietnam/sources/vstb/viet-su-tan-bien-quyen-6.txt"
OUT = "/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch2-clean.txt"

with open(SRC, 'r') as f:
    lines = f.readlines()

# Extract Chapter I: lines 838-1329
ch1 = lines[837:1329]  # 0-indexed
text = ''.join(ch1)

# Remove page markers and running headers
text = re.sub(r'^=== PAGE \d+ ===\s*\n?', '', text, flags=re.MULTILINE)
text = re.sub(r'^VIỆT[- ]NAM CÁCH[- ]MẠNG CẬN[-: ]SỬ\s*\d+\s*\n?', '', text, flags=re.MULTILINE)
text = re.sub(r'^VIỆTNAM CÁCH[- ]MẠNG CẢN[- ]SỬ\s*\d+\s*\n?', '', text, flags=re.MULTILINE)
text = re.sub(r'^VIËT[- ]NAM CÁCH[- ]MẠNG CẬN[- ]SỬ\s*\d+\s*\n?', '', text, flags=re.MULTILINE)
text = re.sub(r'^\d+\s+VỤ KINH-THÀNH THẤT THỦ\s*\n?', '', text, flags=re.MULTILINE)
text = re.sub(r'^\d+\s+VU KINH-THÀNH THẤT THỦ\s*\n?', '', text, flags=re.MULTILINE)
text = re.sub(r'^\d+\s+VỤ KINH-THÂNH THẤT THỦ\s*\n?', '', text, flags=re.MULTILINE)

# Join hyphenated line breaks
text = re.sub(r'(\w)-\s*\n\s*(\w)', r'\1\2', text)

# Fix common OCR issues - batched replacements
fixes = [
    ('TRJIỀU', 'TRIỀU'), ('lỷ-do', 'lý-do'), ('Bäc', 'Bắc'),
    ('thihành', 'thi-hành'), ('bäi-bô', 'bãi-bỏ'), ('phong-tổa', 'phong-tỏa'),
    ('tièu-diêt', 'tiêu-diệt'), ('Viêt-Nam', 'Việt-Nam'), ('Viét-Nam', 'Việt-Nam'),
    ('tôn-phi', 'tổn-phí'), ('}Isle', "d'Isle"), ('vüng', 'vùng'),
    ('tồ-chức', 'tổ-chức'), ('lưn-động', 'lưu-động'), ('nhiền', 'nhiều'),
    ('gian-khồ', 'gian-khổ'), ('uò', 'và'), ('müa', 'mùa'),
    ('thề hoại-động', 'thể hoạt-động'), ('véi', 'với'),
    ('quar-trong', 'quan-trọng'), ('giai-doan', 'giai-đoạn'),
    ('bổ rơi', 'bỏ rơi'), ('chän-nän', 'chán-nản'),
    ('sï-dân', 'sĩ-dân'), ('de Courcÿ', 'de Courcy'),
    ('chánhtrị', 'chính-trị'), ('tưởng lĩnh', 'tướng lĩnh'),
    ('phän-dông', 'phản-động'), ('ngoai-giao', 'ngoại-giao'),
    ('täi-diên', 'tái-diễn'), ('tảo bạo', 'táo bạo'),
    ('chü-dông', 'chủ-động'), ('de Gourcy', 'de Courcy'),
    ('Bäc-viêt', 'Bắc-Việt'), ('thäng', 'tháng'), ('Bäc-kÿ', 'Bắc-kỳ'),
    ('Bắckỳ', 'Bắc-kỳ'), ('khôi-nghïa', 'khởi-nghĩa'),
    ('hoat-dông', 'hoạt-động'), ('vi-tri', 'vị-trí'),
    ('vän-dè', 'vấn-đề'), ('lãnh-lụ', 'lãnh-tụ'),
    ('dng-nhất', 'đúng nhất'), ('gidi-quyét', 'giải-quyết'),
    ('phâi', 'phải'), ('giỗi-qugết', 'giải-quyết'),
    ('uấn- đề', 'vấn-đề'), ('nâm', 'nắm'), ('mac-dich', 'mục-đích'),
    ('khinh -xuất', 'khinh-xuất'), ('bằn-chức', 'bổn-chức'),
    ('kim-chi ngoc-diép', 'kim-chi ngọc-diệp'), ('zã-tắc', 'xã-tắc'),
    ('bách tỉnh', 'bách tính'), ('kiêu-cố', 'kiên-cố'),
    ('nồi dai-bäc', 'nổi đại-bác'), ('vdng ngọc', 'vàng ngọc'),
    ('biệnluận', 'biện-luận'), ('nghỉ rằng', 'nghĩ rằng'),
    ('mäy may', 'mảy may'), ('Täm thực', 'Tầm thực'),
    ('đả rõ', 'đã rõ'), ('hòa hoắn', 'hòa hoãn'),
    ('binh qugền', 'binh quyền'), ('Hoàngthân', 'Hoàng-thân'),
    ('hoàngthành', 'hoàng-thành'), ('Phụ-chánh', 'Phụ-chính'),
    ('bai nước', 'hai nước'), ('quí quốc', 'quý quốc'),
    ('nối lời', 'nói lời'), ('Thông-tông', 'Thống-tướng'),
    ('Thải-Hòa', 'Thái-Hòa'), ('tùy tông', 'tùy tùng'),
    ('tặng phầm', 'tặng phẩm'), ('Tèm thực', 'Tầm thực'),
    ('hốihả', 'hối hả'), ('Tham-biên', 'Tham-biện'),
    ('Son phỏng', 'Sơn-phòng'), ('mật-thảm', 'mật-thám'),
    ('cố ÿ', 'cố ý'), ('miễn cưởng', 'miễn cưỡng'),
    ('bạỏ-hành', 'bạo-hành'), ('đự-định', 'dự-định'),
    ('hỏa - hoãn', 'hòa-hoãn'), ('đảnh', 'đành'),
    ('rỗi oậu', 'rồi sao'), ('Thäi-Nguyên', 'Thái-Nguyên'),
    ('Vo sinh', 'Võ-sinh'), ('tuyềnmộ', 'tuyển-mộ'),
    ('Hồ-Oai', 'Hùng-Oai'), ('Hùng - Duệ', 'Hùng-Duệ'),
    ('tượng-bỉnh', 'tượng-binh'), ('dư-đẩ', 'dư-dật'),
    ('chi-huy', 'chỉ-huy'), ('Trän-xuân-Soan', 'Trần-xuân-Soạn'),
    ('khầu', 'khẩu'), ('khai hổa', 'khai hỏa'),
    ('chỈ-huy', 'chỉ-huy'), ('diéukhièn', 'điều-khiển'),
    ('trọng-phảo', 'trọng-pháo'), ('cüng', 'cũng'),
    ('lui gi', 'lùi giờ'), ('vọng-lâu', 'vọng-lâu'),
    ('nổi hiệu', 'nổi hiệu'), ('Thốngtưởng', 'Thống-tướng'),
    ('thi-uy', 'thị-uy'), ('Sü-quän', 'Sứ-quán'),
    ('man bảo', 'mạn báo'), ('đại- bác', 'đại-bác'),
    ('đữ-dội', 'dữ-dội'), ('Mang-Cà', 'Mang-Cá'),
    ('bất ngò', 'bất ngờ'), ('bổ chạy', 'bỏ chạy'),
    ('vü-khi', 'vũ-khí'), ('ngäp', 'ngáp'), ('gäy', 'gãy'),
    ('thai chân', 'hai chân'), ('hoäng-hôt', 'hoảng-hốt'),
    ('phòngthủ', 'phòng-thủ'), ('đồ đất', 'đổ đất'),
    ('lấp chận', 'lấp chặn'), ('Viét-quân', 'Việt-quân'),
    ('chuyền họng', 'chuyển họng'), ('phóng - thích', 'phóng-thích'),
    ('trùngdrục', 'trùng trục'), ('sụp đồ', 'sụp đổ'),
    ('bất đầu', 'bắt đầu'), ('phẩn-công', 'phản-công'),
    ('Häi-phông', 'Hải-phòng'), ('hàng ngû', 'hàng ngũ'),
    ('chiến-ham', 'chiến-hạm'), ('ảnh lửa', 'ánh lửa'),
    ('Niệc- Nam', 'Việt-Nam'), ('bất kề', 'bất kỳ'),
    ('quânsy', 'quân-sự'), ('nhà ca', 'nhà của'),
    ('tan rä', 'tan rã'), ('cỗ dai-bâc', 'cỗ đại-bác'),
    ('dai-phäo', 'đại-pháo'), ('bộ Hinh', 'bộ Binh'),
    ('triét-thoäi', 'triệt-thoái'), ('giây lưng', 'dây lưng'),
    ('dinhthy', 'dinh thự'), ('ướclượng', 'ước-lượng'),
    ('vữ-khí', 'vũ-khí'), ('bị trọngthương', 'bị trọng-thương'),
    ('Mặc đầu', 'Mặc dầu'), ('khen ngọi', 'khen ngợi'),
    ('non nói', 'non nớt'), ('ái-qnốc', 'ái-quốc'),
    ('chuän-bi', 'chuẩn-bị'), ('minh-chứng', 'minh-chứng'),
    ('thựcdân', 'thực-dân'), ('đồngliêu', 'đồng-liêu'),
    ('tuyêt-ddi', 'tuyệt-đối'), ('hiều lầm', 'hiểu lầm'),
    ('nhận - định', 'nhận-định'), ('Qui-müi', 'Quý-Mùi'),
    ('khôiphục', 'khôi-phục'), ('it ra', 'ít ra'),
    ('kể địch', 'kẻ địch'), ('lịch-ssử', 'lịch-sử'),
    ('phong -trào', 'phong-trào'), ('thời dé', 'thời dễ'),
    ('đàn-ảp', 'đàn-áp'), ('đảơ', 'đảo'),
    ('đứng đắn', 'đúng đắn'), ('sôi nỗi', 'sôi nổi'),
    ('nhỗ', 'nhỏ'), ('thủ lổi', 'thủy lợi'),
    ('giặc nhô', 'giặc nhỏ'), ('chứcvụ', 'chức vụ'),
    ('đốt chính-trị', 'dốt chính-trị'),
    ('nung-nấu đầu:óc', 'nung-nấu đầu óc'),
    ('chiếnlược', 'chiến-lược'), ('Vinh-Yèn', 'Vĩnh-Yên'),
    ('mờ - mờ', 'mờ mờ'), ('Á-Rập', 'Ả-Rập'),
    ('kháng-cbiến', 'kháng-chiến'), ('ViệcNam', 'Việt-Nam'),
    ('Ÿà', 'và'), ('nhiệmvụ', 'nhiệm-vụ'),
    ('nungnấu', 'nung-nấu'), ('chánh-phủ Tàn', 'chánh-phủ Tàu'),
    ('kháögschiến', 'kháng-chiến'), ('luyến tiếc', 'luyến tiếc'),
    ('Âm cộng sự', 'tận tâm cộng sự'),
    ('lắng Tây phương', 'lăng Tây phương'),
    ('lập đượ', 'lập được'), ('công lởn', 'công lớn'),
    ('nh ều', 'nhiều'), ('quên giặc', 'quân giặc'),
    ('khôi uất hận', 'khỏi uất hận'),
    ('địp tấn tôn', 'dịp tấn công'),
    ('cải nhục', 'cái nhục'), ('tưởng Brière', 'tướng Brière'),
    ('FIsle', "d'Isle"), ('Hànội', 'Hà-nội'),
    ('tácgiả', 'tác-giả'), ("L‘Empire d‘Annam", "L'Empire d'Annam"),
    ('Trễ côn hơn không', 'Trễ còn hơn không'),
    ('bât', 'bắt'), ('uà', 'và'), ('phả hoại', 'phá hoại'),
    ('tuyên - bố', 'tuyên-bố'), ('côn', 'còn'),
    ('Tiều-đoàn', 'Tiểu-đoàn'), ('Bắckỷ', 'Bắc-kỳ'),
    ('bỗ', 'bỏ'), ('bất tia', 'bất tín'),
    ('thủ - túc', 'thủ-túc'), ('Đỏ', 'Đó'),
    ('nằm Crétin', 'tên Crétin'), ('bô-binh', 'bộ-binh'),
    ('giän-di', 'giản-dị'), ('it quân tử', 'ít quân tử'),
    ('Hồng- môn hội - gến', 'Hồng-môn hội-yến'),
    ('bất giữa Ng', 'bắt giữa Nghệ'),
    ('gian-muu', 'gian-mưu'), ('sơ hổ', 'sơ hở'),
    ('tùy tòng', 'tùy tùng'), ('Giảm-mụ€', 'Giám-mục'),
    ('Khâm-sử', 'Khâm-sứ'), ('nồ súng', 'nổ súng'),
    ('viện-vỗ tướng', 'viễn-chinh tướng'),
    ('nag', 'nay'), ('cảm - tưởng', 'cảm-tưởng'),
    ('Bửu Kế', 'Bửu-Kế'), ('TÒA KHẨM SỬ', 'TÒA KHẤM SỨ'),
    ('tạp chỉ', 'tạp-chí'), ('Bách Khoa', 'Bách-Khoa'),
    ('co', 'có'), ('bồi bếp', 'bồi bếp'),
    ('thải độ', 'thái-độ'), ('tự kiêu', 'tự kiêu'),
    ('của Đạitướng', 'của Đại-tướng'),
    ('khinh-khi', 'khinh-khỉ'), ('nghỉ', 'nghĩ'),
    ('đạiđội', 'đại-đội'), ('eŠ', 'làm cho'),
    ('đệnhị', 'đệ nhị'), ('đồng-đạc', 'đông-đạc'),
    ('Co-Mậtviện', 'Cơ-mật-viện'), ('tưần', 'tuần'),
    ('phê-chuần', 'phê-chuẩn'),
    ('tầm ăn lá đâu', 'tằm ăn lá dâu'),
    ('Son phỏng', 'Sơn-phòng'),
    ('Cầm-y', 'Cấm-vệ'), ('Kim-ngô', 'Kim-ngô'),
    ('chạy đài', 'chạy dài'), ('ca Tây', 'cửa Tây'),
    ('Sứ-quản', 'Sứ-quán'), ('xâ-giao', 'xã-giao'),
    ('đáng kề', 'đáng kể'), ('tảc-giỗ', 'tác-giả'),
    ('thề đo', 'thể do'), ('khật sự', 'thật sự'),
    ('tháiđộ eùa', 'thái-độ của'), ('cäm-tù', 'cầm-tù'),
    ("'wào", 'vào'), ('Mang Cả', 'Mang Cá'),
    ('toản quân', 'toán quân'), ('tỔi', 'tối'),
    ('phẩi', 'phải'), ('quả mặt', 'qua mặt'),
    ('#6', 'mấy'), ('găng quả', 'căng quá'),
    ('tỉnh-thần', 'tinh-thần'), ('chủ-bại cửa họ', 'chủ-bại của họ'),
    ('(Mì', '(1)'), ('Phấp', 'Pháp'),
    ('thực đân', 'thực-dân'), ('gho', 'cho'),
    ('thốngtrị', 'thống-trị'),
    ('vui-vé', 'vui-vẻ'), ('thị-uy', 'thị-uy'),
    ("Vào' canh", 'Vào canh'),
    ('lính P! châu', 'lính Phi-châu'),
    ('thäy-quân', 'thủy-quân'), ('nhổ', 'nhỏ'),
    ('Tông cộng', 'Tổng cộng'), ('si-quan', 'sĩ-quan'),
    ('dầy đặc', 'dày đặc'), ('lối', 'lúc'),
    ('sảng', 'sáng'), ('rồi lửa đổ bốc', 'rồi lửa đỏ bốc'),
    ('phía,Sử-quán', 'phía Sứ-quán'), ('xông-vào', 'xông vào'),
    ('toän', 'toán'), ('tiàn', 'tiến'),
    ('ảo', 'áo'), ('Dai-Üy', 'Đại-Úy'),
    ('bột', 'bột'), ('đồ đất', 'đổ đất'),
    ('chống đỹ', 'chống đỡ'), ('đạn- được', 'đạn-dược'),
    ('nhà giây thép', 'nhà dây thép'),
    ('J Sau nảy', '(1) Sau này'),
    ('Cầu Mươ sót', 'Cầu Mưu sát'),
    ('§ứ-quán', 'Sứ-quán'), ('lậnh', 'lệnh'),
    ('Tôn-Thất.Lễ', 'Tôn-Thất-Lễ'),
    ('Hãng: hải nhất', 'Hăng-hái nhất'),
    ('thân - binh', 'thân-binh'), ('xôa', 'xõa'),
    ('tòa Sử', 'tòa Sứ'), ('cửa sô', 'cửa sổ'),
    ('đám cổ', 'đám cỏ'), ('bắn đữ', 'bắn dữ'),
    ('Tôn-thất-Liệt', 'Tôn-Thất-Lễ'),
    ('gà gay', 'gà gáy'), ('muctièu', 'mục-tiêu'),
    ('thư hại', 'thư hại'), ('công phả', 'công phá'),
    ('Mang-Câ', 'Mang-Cá'), ('Trungtá', 'Trung-tá'),
    ('va', 'và'), ('Thiến-tá', 'Thiếu-tá'),
    ('mọi.việc', 'mọi việc'), ('tré', 'trẻ'),
    ('tre nô', 'đạn nổ'), ('@Ä', 'khắp'),
    ('da ra', 'đã ra'), ('Mc', 'trong lúc'),
    ('chiến-lũy', 'chiến-lũy'), ('ngồn ngang', 'ngổn ngang'),
    ('cẩn lối', 'cản lối'), ('vá', 'và'),
    ('binh-minh', 'bình-minh'), ('thưa tiếng', 'thưa tiếng'),
    ('cải gì', 'cái gì'), ('kỳ-đài', 'kỳ-đài'),
    ('tiều-đoàn', 'tiểu-đoàn'),
    ('Ngoài.cung-điện', 'Ngoài cung-điện'),
    ('ước-lượng cửa Pháp', 'ước-lượng của Pháp'),
    ('súng t:y', 'súng tây'), ('binhsĩ', 'binh-sĩ'),
    ('kể', 'kẻ'), ('như ÿ muốn', 'như ý muốn'),
    ('Trung-ủy', 'Trung-úy'), ('Trung-üy', 'Trung-úy'),
    ('nề', 'nổ'), ('„tong', 'trong'), ('eù', 'cả'),
    ('đưới', 'đều'), ('cò thể', 'có thể'),
    ('tu-vê', 'tự-vệ'), ('hy - sinh', 'hy-sinh'),
    ('0na', 'vua'), ("đám'", 'dám'), ('mạt-sát', 'mạt-sát'),
    ('họ:', 'họ'), ('trí -thức', 'trí-thức'),
    ('7hành Thuận - hóa', 'Thành Thuận-Hóa'),
    ('dé»', 'đó».'), ('diêt', 'diệt'),
    ('sĩdân', 'sĩ-dân'), ('địp', 'dịp'),
    ('tấn tôn', 'tấn công'),
    ('Đại - Ủy', 'Đại-Úy'), ('thơ', 'thư'),
    ('đứa ra', 'đưa ra'),
    ('Longthuyền', 'Long-thuyền'),
    ('Đại- Úy', 'Đại-Úy'), ('đại - bác', 'đại-bác'),
    ('thän', 'thần'), ('mã tấu', 'mã-tấu'),
    ('đệ nhị Phụ-chánh', 'đệ nhị Phụ-chính'),
    ('Phạm - thận - Duật', 'Phạm-Thận-Duật'),
    ('2#', '2.'),
    # Fix remaining header text
    ('2 VỤ KINH-THÂNH THẤT THỦ', ''),
    ('34 VU KINH-THÀNH THẤT THỦ', ''),
]

for old, new in fixes:
    text = text.replace(old, new)

# Final normalization
text = re.sub(r'\n{4,}', '\n\n\n', text)
text = re.sub(r'\s+([,;:.!?])', r'\1', text)

with open(OUT, 'w') as f:
    f.write(text)

lines_n = [l for l in text.split('\n') if l.strip()]
print(f"OK. Non-blank lines: {len(lines_n)}, Total: {len(text.split(chr(10)))}")
