#!/usr/bin/env python3
"""Final polish pass for ch5-clean.txt"""
with open('/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch5-clean.txt', 'r') as f:
    text = f.read()

fixes = {
    'Länh-sự': 'Lãnh-sự',
    'Hộiđồng': 'Hội-đồng',
    'mệnh-mộtlệnh': 'mệnh-lệnh',
    'mệnh-lệnh của họ': 'mệnh-lệnh của họ',
    'Viên-ngoại-làng': 'Viên-ngoại-lang',
    'Häm-Nghi': 'Hàm-Nghi',
    'Tôn-thấtThuyết': 'Tôn-thất-Thuyết',
    'Tôn-thất Thuyết': 'Tôn-thất-Thuyết',
    'Tôn- thất-Thuyết': 'Tôn-thất-Thuyết',
    'di-chỉéu': 'di-chiếu',
    'dàn bà': 'đàn bà',
    'vi trong': 'vị trong',
    'nhúng tay ào': 'nhúng tay vào',
    'Hän-nghi': 'Hàm-nghi',
    'lỏng một chỉ': 'lòng một dạ',
    'chỉa rẽ': 'chia rẽ',
    'chẳng khác chỉ': 'chẳng khác chi',
    'sợi tợ': 'sợi tơ',
    'Nhà-\nnước': 'Nhà nước',
    'Nhà nước': 'Nhà nước',
    'quảng cáo': 'quảng bá',
    'lời lời': 'lời',
    'kề tội': 'kể tội',
    'kề trên': 'kể trên',
    'đại-kỳ nói': 'đại-ý nói',
    'dé là': 'đó là',
    'Nam-kkỳ': 'Nam-kỳ',
    'Bäc-kkỳ': 'Bắc-kỳ',
    'Trung-kkỳ': 'Trung-kỳ',
    'kkỳ': 'kỳ',
    'chỉêu-thảo-sứ': 'chiêu-thảo-sứ',
    'chỉêu-dụ': 'chiêu-dụ',
    'lựclượng': 'lực-lượng',
    'kề rành-mạch': 'kể rành-mạch',
    'lấy làm tiếc': 'lấy làm tiếc',
    'đẩy-đủ': 'đầy-đủ',
    'Quốc-\n-quận hồng của ngay-chyền': 'Quốc-sử hồng của ngay-chuyền',
    'năm được': 'nắm được',
    'nguy-binh': 'ngụy-binh',
    'chỉ-điểm': 'chỉ-điểm',
    'chùa chỉền': 'chùa chiền',
    'Đại-úy': 'Đại-úy',
    'Thiếu-tưởng': 'Thiếu-tướng',
    'tỉnh-ly': 'tỉnh-lỵ',
    'được phải': 'được phái',
    'dễ-dàng,': 'dễ-dàng.',
    'chiến-': 'chiến-',
    'vô-hiệu-quả': 'vô hiệu-quả',
    'bầy một': 'bày một',
    'dám vua quan': 'đám vua quan',
    'trấn-ĩnh': 'trấn-ỉnh',
    'dé.\nnghị': 'đề-nghị',
    'dé.nghị': 'đề-nghị',
    'nguyên-hàm': 'nguyên-hàm',
    'năm được': 'nắm được',
    'con cỏ mỗi': 'con cờ mồi',
    'có. tương-lài': 'có tương-lai',
    'Pham-vän-Mkỳ': 'Phạm-văn-Mỹ',
    'Boulàngier': 'Boulangier',
    'viở đây': 'vì ở đây',
    '4.Ô00': '40.000',
    '9.Ô00': '9.000',
    '4v.v.Ô0': '40.000',
    'mạnh mạnh hơn': 'mạnh hơn',
    'Đồng-hởi': 'Đồng-Hới',
    'đồi re': 'đổi ra',
    'Té-Xuong': 'Tế-Xương',
    'mờ tối': 'mờ tối',
    'dẻo dai': 'dẻo dai',
    'khäng-chiến': 'kháng-chiến',
    'Quäng-Binh': 'Quảng-Bình',
    'Quäng-trị': 'Quảng-trị',
    'Hà-Tỉnh': 'Hà-Tĩnh',
    'đồi ra': 'đổi ra',
    'Trườnghợp': 'Trường hợp',
    '© lân': 'tương tàn',
    'hàng ngũ': 'hàng ngũ',
    'Tä.lkỳ': 'Tả-lý',
    'äu-sät': 'Án-sát',
    'Đinhduy-Tân': 'Đinh-Duy-Tân',
    'Tốngduy-Tän': 'Tống-Duy-Tân',
    'đồng-bào Công-giáo': 'đồng-bào Công-giáo',
    'chỉ-lưu': 'chi-lưu',
    'Nguyénvắn-Tường': 'Nguyễn-văn-Tường',
    'dàn-áp': 'đàn-áp',
    'năm ấy': 'năm ấy',
    'tỉnh Nghệ': 'tỉnh Nghệ',
    'đại-đội kinh-binh': 'đại-đội kinh-binh',
    'viở': 'vì ở',
    'nối nhau': 'nối nhau',
    'kề thêm': 'kể thêm',
    'thiêuhủy': 'thiêu-hủy',
    'mạnh mạnh hơn': 'mạnh hơn',
    'không khí': 'không khí',
    'nguyên Viên-ngoại-lang': 'nguyên Viên-ngoại-lang',
    'Phan-Quang-Cự': 'Phan-Quang-Cự',
    'Phan-Khắc-Hòa': 'Phan-Khắc-Hòa',
    'Ngụy-Khắc-Kiều': 'Ngụy-Khắc-Kiều',
    'Tham-biện': 'Tham-biện',
    'Tán-lý': 'Tán-lý',
    'Nguyễn-Chánh': 'Nguyễn-Chánh',
    'Cao-Đạt': 'Cao-Đạt',
    'Hàm-thao': 'Hàm-thao',
    'Từ-Dũ': 'Từ-Dũ',
    'thân-hào': 'thân-hào',
}

for old, new in sorted(fixes.items(), key=lambda x: -len(x[0])):
    text = text.replace(old, new)

with open('/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch5-clean.txt', 'w') as f:
    f.write(text)

print(f'Done. {len(text)} chars')
