#!/usr/bin/env python3
"""Second-pass cleaning for Chapter V — fix remaining OCR artifacts."""

import re

with open('/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch5-clean.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# More thorough fixes
fixes = {
    # Title/heading fixes
    'VUA HÂM-NGHI HOẠT': 'VUA HÀM-NGHI HOẠT',
    'HÂM-NGHI HOẠT ĐỘNG Ở HÀ-TĨNH': 'HÀM-NGHI HOẠT ĐỘNG Ở HÀ-TĨNH',
    'Hàm-Nghỉ': 'Hàm-Nghi',
    'HÄM-NGHI': 'HÀM-NGHI',
    
    # OCR letter confusions
    'chỉếnđấu': 'chiến-đấu',
    'chỉến': 'chiến',
    'Trungkkỳ': 'Trung-kỳ',
    'tràn đẩy': 'tràn đầy',
    'binhSĩ': 'binh-sĩ',
    'chỉếc': 'chiếc',
    'chỉluu': 'chi-lưu',
    'vuà': 'vua',
    'Hà-tÏnh': 'Hà-tĩnh',
    'NguyễnChánh': 'Nguyễn-Chánh',
    'Tôn-thất -': 'Tôn-thất-',
    'Länh-binh': 'Lãnh-binh',
    'Kháng-chỉến': 'Kháng-chiến',
    'giấy': 'dãy',
    'côn lệthuộc': 'còn lệ-thuộc',
    'lệthuộc': 'lệ-thuộc',
    'triềuđình': 'triều-đình',
    'Vọngcác': 'Vọng-các',
    'giai-doan': 'giai-đoạn',
    'khỏi nước': 'khỏi nước',
    'đặcbiệt': 'đặc-biệt',
    'khó đầu': 'khó đầu',
    'kể bỏ': 'kẻ bỏ',
    'kể bị': 'kẻ bị',
    'thày': 'thầy',
    'mệnh-': 'mệnh',
    'Dươnglịch': 'Dương-lịch',
    'linh tỉnh': 'lính tỉnh',
    'kéo tới chầu hầu': 'kéo tới chầu hầu',
    'kề tội': 'kể tội',
    'Sơn-Phòng Hà-Tinb': 'Sơn-Phòng Hà-Tĩnh',
    'Ngụy-Khắc-Kiều': 'Ngụy-Khắc-Kiều',
    'Đô-ngg-sử': 'Đô-ngự-sử',
    'Tham-biện': 'Tham-biện',
    'thihành': 'thi-hành',
    'Ít nhiều': 'ít nhiều',
    'chiếu Cần-vương thứ hai': 'chiếu Cần-vương thứ hai',
    'lời của vua': 'lời của vua',
    'thêm một': 'thêm một',
    'Đồng Khánh': 'Đồng-Khánh',
    'Đệ-nhị niên': 'Đệ-nhị niên',
    'tôn-vương': 'tôn-vương',
    'hiệpước giải-hòa': 'hiệp-ước giải-hòa',
    'dänh': 'đánh',
    'chảy': 'cháy',
    'ấn phong vương': 'ấn phong vương',
    'thành.-nội': 'thành-nội',
    'sủng': 'súng',
    'nhà-hiếp': 'nhà-hiếp',
    'quân đân': 'quân dân',
    'thihänh': 'thi-hành',
    'Nghệan': 'Nghệ-an',
    'tiêuđiệt': 'tiêu-diệt',
    'khôi-phuc': 'khôi-phục',
    'tät-nhièn': 'tất-nhiên',
    'dinh-chinh': 'đính-chính',
    'triêt-dè': 'triệt-để',
    'Tü-Dü': 'Từ-Dũ',
    'Đức bà': 'Đức Bà',
    'Thải-hận': 'Thái-hậu',
    'phỉnh gat': 'phỉnh-gạt',
    'bién-cô': 'biến-cố',
    'bạo thiên nghịch dia': 'bạo thiên nghịch địa',
    'Hoäng-tôc': 'Hoàng-tộc',
    'Phu-chänh': 'Phụ-chánh',
    'hư-Irugền': 'hư-truyền',
    'viéc nàg': 'việc nầy',
    'mua Kiến-Phúc': 'vua Kiến-Phúc',
    'biển-cố': 'biến-cố',
    'xẩu ra': 'xảy ra',
    'hoànfoàn': 'hoàn-toàn',
    'Tôn-thät-Thayët': 'Tôn-thất-Thuyết',
    'Nguyễn-uän-Tường': 'Nguyễn-văn-Tường',
    'gâu nên': 'gây nên',
    'củng': 'cùng',
    'một lỏng một chi': 'một lòng một dạ',
    'khiển': 'khiến',
    'cửu Miếu': 'tôn miếu',
    'sợi tợ': 'sợi tơ',
    'Hoäng-thién': 'Hoàng-thiên',
    'häo-tâm': 'hảo-tâm',
    'sóng naụ đã tên': 'sóng dữ đã êm',
    'phuhoa': 'phù-hoa',
    'Viét-gian': 'Việt-gian',
    'đồi bên': 'đôi bên',
    'hồi ảm': 'hồi âm',
    'mạt.sảt': 'mạt-sát',
    'di-nhièn': 'đi-nhiên',
    'thäi-hâu': 'thái-hậu',
    'ải-quốc': 'ái-quốc',
    'cô-động': 'cổ-động',
    'häng-häi': 'hăng-hái',
    'lửa dạy': 'lửa dậy',
    'phéngtrèo': 'phong-trào',
    'Binh-thuân': 'Bình-thuận',
    'lương-giảo': 'lương-giáo',
    'bi-thẩm': 'bi-thảm',
    'sỉ-phu': 'sĩ-phu',
    'tinh thế': 'tình thế',
    'rôi-ren': 'rối-ren',
    'kề xiết': 'kể xiết',
    'Vän-Thân': 'Văn-Thân',
    'khoa-muc': 'khoa-mục',
    'triêt-ha': 'triệt-hạ',
    'Cônggiáo': 'Công-giáo',
    'Trần-quang-Cần': 'Trần-Quang-Cần',
    'Trương-quang-Thủ': 'Trương-Quang-Thủ',
    'Nguyễn-huy-Điền': 'Nguyễn-Huy-Điền',
    'Tổngthống': 'Tổng-thống',
    'khôïi-nghïa': 'khởi-nghĩa',
    'bất đầu': 'bắt đầu',
    'dung-tüng': 'dung-túng',
    'Văn-Thân Nghệ Tĩnh': 'Văn-Thân Nghệ-Tĩnh',
    'ngắm-ngầm': 'ngấm-ngầm',
    'thải-độ': 'thái-độ',
    'rồ-rệt': 'rõ-rệt',
    'lièn-lac': 'liên-lạc',
    'thấtthủ': 'thất-thủ',
    'Có lễ': 'Có lẽ',
    'vịtrí': 'vị-trí',
    'vô-ich': 'vô-ích',
    'nhàn-sĩ': 'nhân-sĩ',
    'Sơn-Phỏng': 'Sơn-phòng',
    'Nghĩa-hội': 'Nghĩa-hội',
    'bức nh-thành': 'bức tỉnh thành',
    'Tuän-Vü': 'Tuần-Vũ',
    'Bố-chá£n': 'Bố-chánh',
    'Hä-thüc-Quän': 'Hà-Thúc-Quán',
    'Trüng-lôc': 'Trung-lộc',
    'tan rä': 'tan rã',
    'tnh-ly': 'tỉnh-lỵ',
    'dày đẳng': 'đấy đẳng',
    'van-miéu': 'văn-miếu',
    'chiêu-thão-sử': 'chiêu-thảo-sứ',
    'kếtliễu': 'kết-liễu',
    'Tỉ-trựckỷ': 'Tả-trực kỳ',
    'Tuyênẩy': 'Tuyên-ủy',
    'đạithần': 'đại thần',
    'hièu-thi': 'hiểu-thị',
    'đẳng Cần-vương': 'đảng Cần-vương',
    'thúc đầy': 'thúc đẩy',
    'sĩdân': 'sĩ-dân',
    'thôa-hiép': 'thỏa-hiệp',
    'Quäng-Ngäi': 'Quảng-Ngãi',
    'Khänh-hôa': 'Khánh-Hòa',
    'Trän-bä-Lôc': 'Trần-bá-Lộc',
    'chiën-': 'chiến-',
    'ich đài rộng': 'liên-đài rộng',
    'chät-chè': 'chặt-chẽ',
    'kinh tổm': 'kinh tởm',
    'cải chước': 'cái chước',
    'lấp dé giết dé': 'lấp dế giết dế',
    'hiéu-nghiêm': 'hiệu-nghiêm',
    'Tbáng': 'Tháng',
    'Pinh-hợi': 'Đinh-Hợi',
    'Phỏdướng': 'Phó-tướng',
    'nghĩaquân': 'nghĩa-quân',
    'cử-mục': 'cựu-mục',
    'Phü-Yèn': 'Phú-Yên',
    'Ẩn.sát': 'Án-sát',
    'Huÿnh-Côn': 'Huỳnh-Côn',
    'Tä.lÿ': 'Tả-lý',
    'Luong-xuân-Huyèn': 'Lương-xuân-Huyền',
    'Cao-Đệ': 'Cao-Đệ',
    'Bố-chảnh': 'Bố-chánh',
    'An-sat': 'Án-sát',
    'Tôn<hät-Bâ': 'Tôn-thất-Bá',
    'än-sät': 'Án-sát',
    'Đinh-duy-Tân': 'Đinh-Duy-Tân',
    'câch-mang': 'cách-mạng',
    'Tống-duy-Tän': 'Tống-Duy-Tân',
    'Hươngkhê': 'Hương-Khê',
    'HùngLĩnh': 'Hùng-Lĩnh',
    'trường hoat-dông': 'trường hoạt-động',
    'khángdịch': 'kháng-địch',
    'kề rành - mạch': 'kể rành-mạch',
    'nồi tiếng': 'nổi tiếng',
    'anh-düng': 'anh-dũng',
    'thám-phục': 'thán-phục',
    'Trung - kỷ': 'Trung-kỳ',
    'lam tiết': 'làm tiếc',
    'Quốc--quận hồng của ngay-chyền': 'quốc-sử hồng của ngay-chuyền',
    'ghỉ chép': 'ghi chép',
    'Miễn Bắc': 'miền Bắc',
    'khôïnghia': 'khởi-nghĩa',
    'dàiđược': 'dài được',
    'trổ ra': 'trở ra',
    'địalỷ': 'địa-lý',
    'đuồi theo': 'đuổi theo',
    'tỉnh-ly': 'tỉnh-ly',
    'it kể': 'ít kẻ',
    'thuở đỏ': 'thuở đó',
    'lai còn': 'lại còn',
    'nộituyến': 'nội-tuyến',
    'đốt phả': 'đốt phá',
    'Công-giäo': 'Công-giáo',
    'chi-diém': 'chỉ-điểm',
    'thịsát': 'thị-sát',
    'tải lập': 'tái lập',
    'Chợ -Säi': 'Chợ-Sãi',
    'sầm-uất': 'sầm-uất',
    'gi ổa': 'giữa',
    'Chủngviện': 'Chủng-viện',
    'giảo-dân': 'giáo-dân',
    'Bäi-Son': 'Bãi-Sơn',
    'Công-giảo': 'Công-giáo',
    'năm ruôi': 'năm rưỡi',
    'giảo-đân': 'giáo-dân',
    'giảo-đường': 'giáo-đường',
    'Luong-giäo': 'Lương-giáo',
    'dai-dôi': 'đại-đội',
    'thắm': 'thăm',
    'Cam -lộ': 'Cam-lộ',
    'viở đây': 'vì ở đây',
    'điện -tín': 'điện-tín',
    'Giáosĩ': 'Giáo-sĩ',
    'kết- quả': 'kết-quả',
    'khả - quan': 'khả-quan',
    'Thiếu-tưởng': 'Thiếu-tướng',
    'phànnàn': 'phàn-nàn',
    'ần núp': 'ẩn núp',
    'Bãi - Đức': 'Bãi-Đức',
    'Cửa Vé': 'Cửa Vẽ',
    'luu-vyc': 'lưu-vực',
    'chi-lwu': 'chi-lưu',
    'thäo-luân': 'thảo-luận',
    'phối:hợp': 'phối-hợp',
    'công-tâc': 'công-tác',
    'rảirác': 'rải-rác',
    'khấp nơi': 'khắp nơi',
    'vồilôi': 'với lôi',
    'it nhiền': 'ít nhiều',
    'Kháng:chiến': 'Kháng-chiến',
    'bâo-vé': 'bảo-vệ',
    'đả.đảo': 'đả-đảo',
    'chánh-sảchthì': 'chánh-sách thì',
    'cỏ thề': 'có thể',
    'cổ một': 'có một',
    'nồi da xáo thịt': 'nồi da xáo thịt',
    'thủ-túc tương': 'thủ-túc tương',
    'cỏ thê': 'có thể',
    'chiến.sĩ': 'chiến-sĩ',
    'đàng khác': 'đằng khác',
    'Đảng tiếc thay': 'Đáng tiếc thay',
    'NHÜNG': 'NHỮNG',
    'triêu-dinh': 'triều-đình',
    'lo-ngai': 'lo-ngại',
    'trấn-ĩnh tinb-thän': 'trấn-ĩnh tinh-thần',
    'dé.nghị': 'đề-nghị',
    'bầy cuộc': 'bày cuộc',
    'danh-nghïa': 'danh-nghĩa',
    'linh Pháp': 'lính Pháp',
    'Quâng-Binh': 'Quảng-Bình',
    'hiêu-quà': 'hiệu-quả',
    'phẩi': 'phải',
    'cổ gắng': 'cố gắng',
    'quỷ kế': 'quỷ kế',
    'Tôngtrấn': 'Tổng-trấn',
    'Hà-tỉnh': 'Hà-tĩnh',
    'hỏng loi-dung': 'hòng lợi-dụng',
    'êm địu': 'êm dịu',
    'Phô-mä': 'Phó-mã',
    'Hoàng-tả-Viêm': 'Hoàng-tá-Viêm',
    'đảng kề': 'đáng kể',
    'Thựcdân': 'Thực-dân',
    'Vi sao': 'Vì sao',
    'Hoàngtá-Viêm': 'Hoàng-tá-Viêm',
    'nởi tiếng': 'nổi tiếng',
    'chiến-sỉ': 'chiến-sĩ',
    'cäm-tinh': 'cảm-tình',
    'si-dân': 'sĩ-dân',
    'con cỏ mỗi': 'con cờ mồi',
    'nghi-ngai': 'nghi-ngại',
    'nguyênhàm': 'nguyên-hàm',
    'täi-dung': 'tái-dụng',
    'chiêu-đụ': 'chiêu-dụ',
    'cận-thần': 'cận-thần',
    'twong-lai': 'tương-lai',
    'Pham-vän-Mÿ': 'Phạm-văn-Mỹ',
    'Minh-cim': 'Minh-Cầm',
    'Trương quangNgọc': 'Trương-quang-Ngọc',
    'quốclộ': 'quốc-lộ',
    'cứ-điềm': 'cứ-điểm',
    'khé-khän': 'khó-khăn',
    'phuc-kich': 'phục-kích',
    'quan-lai': 'quan-lại',
    'Phäp': 'Pháp',
    'di-chuyèn': 'di-chuyển',
    'trụsở': 'trụ-sở',
    'Quäng-Khè': 'Quảng-Khê',
    'Ha-Tĩnh': 'Hà-Tĩnh',
    'chỈhuy': 'chỉ-huy',
    'tiềnđồn': 'tiền-đồn',
    'xuất-phát binh.sĩ': 'xuất-phát binh-sĩ',
    'CẢ bai bên': 'Cả hai bên',
    'thúcthủ': 'thúc-thủ',
    'Ké-viém': 'Kế-Viêm',
    'đồi ra': 'đổi ra',
    'Trần-kếXương': 'Trần-Kế-Xương',
    'Té-Xuong': 'Tế-Xương',
    'giäi-nguy': 'giải-nguy',
    'mở tối': 'mờ tối',
    'đảnh đẹp': 'đánh dẹp',
    'toàn điện': 'toàn diện',
    'Vi lý-do': 'Vì lý-do',
    'kề tới': 'kể tới',
    'Đồng-hởi': 'Đồng-Hới',
    'Võ cử': 'Võ-cử',
    'Nguyễn viết Tôn': 'Nguyễn-Viết-Tôn',
    'chi-tiét': 'chi-tiết',
    'đưới đây': 'dưới đây',
    'tòng vong': 'tòng-vong',
    'lần lút': 'lẩn lút',
    'cồn nhặt': 'còn nhặt',
    'cải võng': 'cái võng',
    'kề cả': 'kể cả',
    'oũng': 'cũng',
    'Đã thé': 'Đã thế',
    'Trần xuân Soạn': 'Trần-xuân-Soạn',
    'càng càng': 'càng',
    'lim ra': 'tìm ra',
    'đảm': 'đám',
    'Tü-tài Phòng': 'Tú-tài Phòng',
    'đây lui': 'đẩy lui',
    'si quan': 'sĩ quan',
    'Tham-biện sử-qguán': 'Tham-biện sứ-quán',
    'Thiểu-tả': 'Thiếu-tá',
    'Kháng chiến.': 'Kháng-chiến',
    'ho gián': 'dán',
    'thỏa mạ': 'thoá mạ',
    'cỏ kỀ': 'có kể',
    'Nguyễn-hữn Độ': 'Nguyễn-hữu-Độ',
    'Co mật-viện': 'Cơ-mật-viện',
    'Tön-thất-Thuyết': 'Tôn-thất-Thuyết',
    'sồ Tên Thất': 'sổ Tôn-Thất',
    'cải qua': 'cải sang',
    'sắc-dụ đưởi đời': 'sắc-dụ dưới đời',
    'Khẩi-Định': 'Khải-Định',
    'phương điện': 'phương diện',
    'linh tụ': 'lĩnh-tụ',
    'Hàm-nghỉ': 'Hàm-nghi',
    'Hàm-Nghỉ': 'Hàm-Nghi',
    'Hàm-Nghi (': 'Hàm-Nghi (',
    'vua Hàm': 'vua Hàm',
    'Nghì': 'Nghi',
}

# Apply fixes sorted by length (longest first)
for old, new in sorted(fixes.items(), key=lambda x: -len(x[0])):
    text = text.replace(old, new)

# Fix remaining fragmented issues
# Remove spurious hyphens at line breaks we missed
text = re.sub(r'(\w)-\n(\w)', r'\1\2', text)

# Fix hyphenated Vietnamese words - ensure proper hyphenation
# đẩy should be đầy in context "tràn đẩy" -> check again
text = text.replace('tràn đẩy', 'tràn đầy')

# Fix specific spacing issues
text = text.replace('đấy ,ngồn', 'đấy, ngồn')
text = text.replace('đấy,ngồn', 'đấy, ngồn')

# Fix "bè :cho" -> "bè: cho" -> "bè cho"
text = text.replace('bè:cho', 'bè cho')
text = text.replace('bè :cho', 'bè cho')

# Fix các chức dưới cùng
# Fix "v.v..." -> "v.v."
text = re.sub(r'v\.v\.\.\.', 'v.v.', text)

# Fix multiple periods
text = re.sub(r'\.{2,}', '...', text)

# Fix multiple spaces
text = re.sub(r'  +', ' ', text)

# Remove trailing spaces
lines = text.split('\n')
lines = [l.rstrip() for l in lines]
text = '\n'.join(lines)

# Normalize blank lines
text = re.sub(r'\n{3,}', '\n\n', text)

with open('/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch5-clean.txt', 'w', encoding='utf-8') as f:
    f.write(text)

print(f"Final cleaned: {len(text)} chars, {len(text.split(chr(10)))} lines")
