#!/usr/bin/env python3
"""
Final comprehensive OCR cleanup for Chapter IX.
Handles all remaining OCR artifacts systematically.
"""
import re

def final_clean(text):
    # === Remove remaining running headers ===
    # Pattern: VIỆT-NAM CÁCH-MẠNG CẬN-SỬ 125
    text = re.sub(r'^VIỆ[TL]-NAM C[AÂ]CH-M[AU]NG C[ẬA]N-S[UỬ] \d{2,3}\n', '', text, flags=re.MULTILINE)
    text = re.sub(r'^VIỆ[TL]-NAM CÂCH-MANG CẬN-SỬ \d{2,3}\n', '', text, flags=re.MULTILINE)
    text = re.sub(r'^VIỆ[TL].*CẬN.SỬ \d{2,3}\n', '', text, flags=re.MULTILINE)
    
    # Remove orphan page-number + title lines
    text = re.sub(r'^\d{2,3} CUỘC KHỞI[^ ]*NGHĨA [A-Z].*\n', '', text, flags=re.MULTILINE)
    text = re.sub(r'^\d{2,3} TIỀU-SỬ [A-Z].*\n', '', text, flags=re.MULTILINE)
    text = re.sub(r'^\d{2,3} ÔNG TÚ [A-Z].*\n', '', text, flags=re.MULTILINE)
    
    # ===========================================
    # Systematic OCR fixes
    # ===========================================
    
    # --- Tone marks on vowels ---
    # chí -> chỉ (when it's "only", not "intelligence")
    # Simple word replacements
    
    fix_map = {
        # Space issues
        'chỉến': 'chiến',
        'chỉếnlược': 'chiến lược',
        'khồng-ché': 'không-chế',
        'khồng': 'không',
        'Khồng': 'Không', 
        'giao thồng': 'giao thông',
        'thồng': 'thông',
        'chũngquanh': 'chung quanh',
        'cải thế': 'cái thế',
        'cải gốc': 'cái gốc',
        'cải hồ': 'cái hồ',
        'cải lũy': 'cái lũy',
        'Địaphương.': 'Địa phương',
        'Mkỳ-Khè': 'Mỹ-Khè',
        'tinh Thanh-Hóa': 'tỉnh Thanh-Hóa',
        'noi phăt-lich': 'nơi phát tích',
        'nh Ninh-Bình': 'tỉnh Ninh-Bình',
        'Hoat-Giang': 'Hoạt-Giang',
        'độcđạo': 'độc đạo',
        'sông. đào': 'sông đào',
        'Dai-Lai': 'Đại-Lai',
        'khủ đỏ': 'cả khu đỏ',
        'Ba-đình': 'Ba-Đình',
        'cẩn lối': 'cản lối',
        'đào bào': 'đào bầu',
        'côngsự': 'công sự',
        'co-giéi': 'cơ giới',
        'chỉến đấu': 'chiến đấu',
        'phần-phối': 'phân phối',
        'Binh-công-Trăng': 'Đinh-công-Tráng',
        'chỉến sỉ': 'chiến sĩ',
        'can-dâm': 'can đảm',
        'Thiếtlập': 'Thiết lập',
        'sỉ-quan': 'sĩ quan',
        'Nguyễn-Khế': 'Nguyễn-Khế',
        'lĩnh việc': 'lãnh việc',
        'điều khiền': 'điều khiển',
        'Đốchọc': 'Đốc học',
        'Đinh-công-Trảng': 'Đinh-công-Tráng',
        'Nguyén-Khè': 'Nguyễn-Khế',
        'Tuăn-vư': 'Tuần vũ',
        'Nguyễn Bat-Nô': 'Nguyễn Bá-Nô',
        'Tỉnh-gia': 'Tĩnh-gia',
        'Tồng-Đốc': 'Tổng-Đốc',
        'Bố-chánh': 'Bố chánh',
        'Ngô-xuân-Quỷnh': 'Ngô-xuân-Quỹnh',
        'Tri-huyên': 'Tri huyện',
        'nhiệtHệt': 'nhiệt liệt',
        'công-tác': 'công tác',
        'được phần-phối': 'được phân phối',
        'Binh-công-Trăng': 'Đinh-công-Tráng',
        'Trảng': 'Tráng',
        'Trāng': 'Tráng',
        'đúng theo': 'đúng theo',
        'Đứng trong': 'Đứng trong',
        'ro lợn': 'rọ lợn',
        'trải lai': 'trái lại',
        'bền ngoài': 'bên ngoài',
        'Ba-Đinh': 'Ba-Đình',
        'mênh-mông': 'mênh mông',
        'quốclộ': 'quốc lộ',
        'Thanh-Hỏa': 'Thanh-Hóa',
        'Đại-tá': 'Đại tá',
        'tháng chap': 'tháng chạp',
        'mụcđích': 'mục đích',
        'tiếptế': 'tiếp tế',
        'phòng -tuyến': 'phòng tuyến',
        'trong-phăo': 'trọng pháo',
        'lục -quân': 'lục quân',
        'rât': 'rát',
        'vitri': 'vị trí',
        'đạiđội': 'đại đội',
        'Bắckỷ': 'Bắc kỳ',
        'đồn lễ': 'đồn lũy',
        'him': 'him',  # keep
        'Thiéu-ưy': 'Thiếu úy',
        'tồn thất': 'tổn thất',
        'khả gan dạ': 'khá gan dạ',
        'Thiểu-úy': 'Thiếu úy',
        'Thiéuưy': 'Thiếu úy',
        'dièu-khiên': 'điều khiển',
        'xa ra': 'bắn ra',
        'binh sỉ': 'binh sĩ',
        'vân thúc': 'vẫn thúc',
        'dao': 'dao',
        'hối-thúc': 'hối thúc',
        'ráoriết': 'ráo riết',
        ':nình': 'rồi',
        'triệtthoái': 'triệt thoái',
        'truy-kich': 'truy kích',
        'ảp-dụng': 'áp dụng',
        'quân-số': 'quân số',
        'đồ thihănh': 'để thi hành',
        'thihănh': 'thi hành',
        'Thủy-quân': 'Thủy quân',
        'biền': 'biển',
        'khả đông': 'khá đông',
        'Phong-tôa': 'Phong tỏa',
        'bộ - bình': 'bộ binh',
        'Thiếutá': 'Thiếu tá',
        'Đạiđội': 'Đại đội',
        'Thiéu-tà': 'Thiếu tá',
        'sư-đoàn': 'sư đoàn',
        'ngoan-quôc': 'ngoại quốc',
        'dai-dôi': 'đại đội',
        'tiềuđoàn': 'tiểu đoàn',
        'bô-binh': 'bộ binh',
        'Phichâu': 'Phi châu',
        'đại đội': 'đại đội',
        'đổ bộ': 'đổ bộ',
        'Thiéu-ưy': 'Thiếu úy',
        'thuyền-trưởng': 'thuyền trưởng',
        'Phăo-binh': 'Pháo binh',
        'khầu': 'khẩu',
        'đại- bác': 'đại bác',
        'cổ 95': 'cỡ 95',
        'Thiéu-tà': 'Thiếu tá',
        'đạibác': 'đại bác',
        'thủy quân': 'thủy quân',
        'pháo binh': 'pháo binh',
        'Hotchiss': 'Hotchkiss',
        '1ỗ người': '18 người',
        'diêu-khiên': 'điều khiển',
        'Thiếu-tả': 'Thiếu tá',
        'Trung-ưy': 'Trung úy',
        'phụtrách': 'phụ trách',
        'đưới quyền': 'dưới quyền',
        'Nguy-binh': 'Ngụy binh',
        'khố xanh': 'khố xanh',
        'phongtổa': 'phong tỏa',
        'tưởng': 'tướng',
        'nội, ngoại': 'nội ngoại',
        'giặc thiệt hại': 'giặc thiệt hại',
        'hiềm-yếu': 'hiểm yếu',
        'đông-hào': 'đồng hào',
        'dân-sự': 'dân sự',
        'phòng ngự': 'phòng ngự',
        'khổng-lồ': 'khổng lồ',
        'nguy-dân': 'ngụy dân',
        '20 kilô': '20 kilô',
        'cậy': 'cậy',
        'tập-trung': 'tập trung',
        'trông thấy': 'trông thấy',
        'đã trông thấy': 'đã trông thấy',
        'được trông thấy': 'được trông thấy',
        'người ta trông': 'người ta trông',
        'chỉến lược': 'chiến lược',
        'lưỡng-kỳ': 'lưỡng kỳ',
        'năm giữ': 'nắm giữ',
        'lỉnh-tụ': 'lãnh tụ',
        'thuyền mành': 'thuyền mành',  # already correct
        'ghỉ tên': 'ghi tên',
        'Mkỳ-Khè': 'Mỹ-Khè',
        'Mậu-Thịnh': 'Mậu-Thịnh',
        'ngập đầu': 'ngập đầu',
        'đồng lầy ngừng lại': 'đồng lầy ngừng lại',
        'trẻ xanh': 'tre xanh',
        'hàng ngàn': 'hàng ngàn',
        'tỉnh binh': 'tỉnh binh',
        'Kháng-chỉến': 'Kháng chiến',
        'dân đinh': 'dân đinh',
        'những. phương': 'những phương',
        'mới. biết': 'mới biết',
        'cải gốc': 'cái gốc',
        'cải lũy': 'cái lũy',
        'tỉnh - trạng': 'tình trạng',
        'khả - năng': 'khả năng',
        'tỉnh-thân': 'tinh-thần',
        'triêu-dình': 'triều đình',
        'sï': 'sĩ',
        'Sï': 'Sĩ',
        'khäng': 'kháng',
        'Khäng': 'Kháng',
        'thät': 'thất',
        'khl': 'khi',
        'nghiêm-nhiên': 'nghiêm nhiên',
        'toan-bô': 'toàn bộ',
        'tranh sống': 'tranh sống',
        'tuyệt-vong': 'tuyệt vọng',
        'quật khởi': 'quật khởi',
        'giầu mạnh': 'giàu mạnh',
        'mần râu': 'mần râu',  # keep
        'bôi-phăn': 'bội phần',
        'liên-mièn': 'liên miên',
        'tinhthần': 'tinh thần',
        'thôn-tinh': 'thôn tính',
        'tập-trủng': 'tập trung',
        'cải lũy': 'cái lũy',
        'toan-bô': 'toàn bộ',
        'bai miền': 'hai miền',
        'Bắckỳ': 'Bắc kỳ',
        'đảng kề': 'đáng kể',
        'hièm trở': 'hiểm trở',
        'dia-dièm': 'địa điểm',
        'cồ-họng': 'cửa họng',
        'không-ché': 'không chế',
        'sän-xuât': 'sản xuất',
        'khoa-mục': 'khoa mục',
        'đề cắt đứt': 'để cắt đứt',
        'thề tiện lơi': 'thể tiện lợi',
        'tiện loi': 'tiện lợi',
        'thuyền mành': 'thuyền mành',
        'bị đánh bạt': 'bị đánh bật',
        'Hèng-Linh': 'Hùng-Linh',
        'Hüng-Linh': 'Hùng-Linh',
        'bièu-duong': 'biểu dương',
        'quật cường': 'quật cường',
        'Tông-duy-Tân': 'Tông-duy-Tân',
        'Bãi-Sậy': 'Bãi-Sậy',
        'Hoàng-bất-Đạt': 'Hoàng-bật-Đạt',
        'Đinh-công:Tráng': 'Đinh-công-Tráng',
        'khổi nghĩa': 'khởi nghĩa',
        'khởi nghïa': 'khởi nghĩa',
        'Phanđình-Phùng': 'Phan-đình-Phùng',
        'Yên-Thế': 'Yên-Thế',
        'Hoàng-hoa-Thám': 'Hoàng-hoa-Thám',
        'Ba-Dinh': 'Ba-Đình',
        'Tôn-thấtThuyết': 'Tôn-thất-Thuyết',
        'hịch Cần-vương': 'hịch Cần Vương',
        'thôn-tinh': 'thôn tính',
        'toan-bô': 'toàn bộ',
        'hào-mục': 'hào mục',
        'Thanh-héa': 'Thanh-Hóa',
        'giáp-giới': 'giáp giới',
        'sông Đà': 'sông Đà',
        'Nam-hải': 'Nam Hải',
        'đài từ': 'dài từ',
        'Ninh-Binh': 'Ninh-Bình',
        'Thanh-Hóa': 'Thanh-Hóa',
        'sùng chiến': 'sùng chiến',
        'nhân-sự': 'nhân sự',
        'săn-xuât': 'sản xuất',
        'nãm': 'năm',
        'xóm Gỗ': 'xóm Gỗ',
        'chợ CHiều': 'chợ Chiều',
        'Quản - cau': 'Quản-cau',
        'quốclộ': 'quốc lộ',
        'thânHín': 'thân tín',
        'khôi-phuc': 'khôi phục',
        'trọngthương': 'trọng thương',
        'cơng': 'công',
        'Lèthành-Binh': 'Lê-thành-Bính',
        'Phúyên': 'Phú yên',
        'tuẫn liết': 'tuẫn tiết',
        'Nguyễn-hãoSự': 'Nguyễn-hảo-Sự',
        'kể khác': 'kẻ khác',
        'Quéc-khănh': 'Quốc khánh',
        'Hiến-pháp': 'Hiến pháp',
        'chánh-quyền': 'chính quyền',
        'Phú-yên và đồng-bào tinh': 'Phú-yên và đồng-bào tỉnh',
        'bổ ra': 'bỏ ra',
        'tuyên-duong': 'tuyên dương',
        'trong-thê': 'trọng thể',
        'bỏ hoang': 'bỏ hoang',
        'siêu sanh': 'siêu sinh',
        'tịnh độ': 'tịnh độ',
        'cảnh-giác': 'cảm giác',
        'dinh-thy': 'dinh thự',
        'Phé-Báng': 'Phó bảng',
        'đao-hanh': 'đạo hạnh',
        'dao-hanh': 'đạo hạnh',
        'Hông-lô tự-Khanh': 'Hồng-lô tự Khanh',
        'biếncố': 'biến cố',
        'Tân-sở': 'Tân sở',
        'trường-kỳ': 'trường kỳ',
        'độngviên': 'động viên',
        'sỉ-phu': 'sĩ phu',
        'thân-hào': 'thân hào',
        'nghữĩađoàn': 'nghĩa đoàn',
        'dông-huong': 'đồng hương',
        'thiếtlập': 'thiết lập',
        'cơ-quan': 'cơ quan',
        'võ khí': 'vũ khí',
        'luyéntâp': 'luyện tập',
        'Trung-lôc': 'Trung Lộc',
        'Qué-son': 'Quế Sơn',
        'thoát-ly': 'thoát ly',
        'phân-dông': 'phản động',
        'Đồng.Khánh': 'Đồng-Khánh',
        'đông-chi': 'đồng chí',
        'Quäng-ngäi': 'Quảng Ngãi',
        'nghĩa hội': 'nghĩa hội',
        'phân': 'phản',
        'hiều biết': 'hiểu biết',
        'nghĩa đoàn': 'nghĩa đoàn',
        'Phụ-đạo': 'Phụ đạo',
        'Kiên-Phúc': 'Kiến-Phúc',
        'Hàm-nghi': 'Hàm-Nghi',
        'mưu tính': 'mưu tính',
        'việc lớn': 'việc lớn',
        'đồng mình': 'đồng minh',
        'địa-phương': 'địa phương',
        'thân sĩ': 'thân sĩ',
        'hào mục': 'hào mục',
        'chịu ra ứng nghĩa': 'chịu ra ứng nghĩa',
        'che-chở': 'che chở',
        'rừng rú': 'rừng rú',
        'ruộng vườn': 'ruộng vườn',
        'nam phụ': 'nam phụ',
        'lão ấu': 'lão ấu',
        'chứng kiến': 'chứng kiến',
        'cảnh-tượng': 'cảnh tượng',
        'gia-đình': 'gia đình',
        'lầm than': 'lầm than',
        'súng đạn': 'súng đạn',
        'đạn pháo': 'đạn pháo',
        'nông dân': 'nông dân',
        'chiến-sĩ': 'chiến sĩ',
        'tàn ác': 'tàn ác',
        'tàn sát': 'tàn sát',
        'thiêu hủy': 'thiêu hủy',
        'phải chịu': 'phải chịu',
        'khóc than': 'khóc than',
        'oán thán': 'oán thán',
        'thù địch': 'thù địch',
        'chống trả': 'chống trả',
        'anh dũng': 'anh dũng',
        'quật cường': 'quật cường',
        'lẫm liệt': 'lẫm liệt',
        'hi sinh': 'hy sinh',
        'hy sinh': 'hy sinh',
        'tấm gương': 'tấm gương',
        'sáng ngời': 'sáng ngời',
        'non sông': 'non sông',
        'đất nước': 'đất nước',
        'tổ quốc': 'tổ quốc',
        'độc lập': 'độc lập',
        'tự do': 'tự do',
        'còn nhớ mãi': 'còn nhớ mãi',
        'tiếng thơm': 'tiếng thơm',
        'muôn đời': 'muôn đời',
    }
    
    for k, v in fix_map.items():
        text = text.replace(k, v)
    
    # Fix spacing around punctuation
    text = re.sub(r'\s*([,.;:!?])\s*', r'\1 ', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    # Remove orphan footnotes markers like (1), (2) that are just numbers
    text = re.sub(r'\([0-9]\) ?\n', '\n', text)
    
    # Fix (1 at line start followed by reference
    text = re.sub(r'^\([0-9]\) ', '', text, flags=re.MULTILINE)
    
    return text

def main():
    path = '/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch9-clean.txt'
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    
    cleaned = final_clean(text)
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(cleaned)
    
    lines = len(cleaned.split('\n'))
    chars = len(cleaned)
    print(f"Final clean pass done. Lines: {lines}, Chars: {chars}")
    print(f"Writing to {path}")

if __name__ == '__main__':
    main()
