#!/usr/bin/env python3
"""Clean Chapter I of VSTB Volume 6. Strips page markers, running headers, 
joins hyphenated line breaks, fixes common OCR diacritic errors."""
import re, sys

INPUT = sys.argv[1] if len(sys.argv) > 1 else "/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch2-clean.txt"
OUTPUT = sys.argv[2] if len(sys.argv) > 2 else INPUT

with open(INPUT, 'r') as f:
    text = f.read()

# Remove page markers
text = re.sub(r'^=== PAGE \d+ ===\n?', '', text, flags=re.MULTILINE)

# Remove header lines (various OCR variants)
for pat in [
    r'^VIỆT[- ]NAM CÁCH[- ]MẠNG CẬN[-: ]SỬ\s*\d+\s*\n?',
    r'^VIỆT[- ]NAM CÁCH[- ]MẠNG CẢN[- ]SỬ\s*\d+\s*\n?',
    r'^VIỆTNAM CÁCH[- ]MẠNG CẢN[- ]SỬ\s*\d+\s*\n?',
    r'^VIËT[- ]NAM CÁCH[- ]MẠNG CẬN[- ]SỬ\s*\d+\s*\n?',
    r'^\d+\s+VỤ KINH-THÀNH THẤT THỦ\s*\n?',
]:
    text = re.sub(pat, '', text, flags=re.MULTILINE)

# Join hyphenated line breaks: word at EOL followed by word
text = re.sub(r'(\w)-\s*\n\s*(\w)', r'\1\2', text)

# Fix common OCR errors (most impactful first)
ocr_fixes = {
    'TRJIỀU': 'TRIỀU',
    'lỷ-do': 'lý-do',
    'Bäc-kinh': 'Bắc-kinh',
    'Bäc-kÿ': 'Bắc-kỳ',
    'Bäc-viêt': 'Bắc-Việt',
    'thihành': 'thi-hành',
    'bäi-bô': 'bãi-bỏ',
    'phong-tổa': 'phong-tỏa',
    'tièu-diêt': 'tiêu-diệt',
    'Viêt-Nam': 'Việt-Nam',
    'Viét-Nam': 'Việt-Nam',
    'tôn-phi': 'tổn-phí',
    '}Isle': "d'Isle",
    'vüng': 'vùng',
    'tồ-chức': 'tổ-chức',
    'lưn-động': 'lưu-động',
    'nhiền': 'nhiều',
    'gian-khồ': 'gian-khổ',
    'uò': 'và',
    'müa': 'mùa',
    'thề hoại-động': 'thể hoạt-động',
    'véi': 'với',
    'quar-trong': 'quan-trọng',
    'giai-doan': 'giai-đoạn',
    'bổ rơi': 'bỏ rơi',
    'chän-nän': 'chán-nản',
    'sï-dân': 'sĩ-dân',
    'de Courcÿ': 'de Courcy',
    'chánhtrị': 'chính-trị',
    'tưởng lĩnh': 'tướng lĩnh',
    'phän-dông': 'phản-động',
    'ngoai-giao': 'ngoại-giao',
    'täi-diên': 'tái-diễn',
    'tảo bạo': 'táo bạo',
    'chü-dông': 'chủ-động',
    'de Gourcy': 'de Courcy',
    'thäng': 'tháng',
    'Bắckỳ': 'Bắc-kỳ',
    'khôi-nghïa': 'khởi-nghĩa',
    'hoat-dông': 'hoạt-động',
    'vi-tri': 'vị-trí',
    'vän-dè': 'vấn-đề',
    'lãnh-lụ': 'lãnh-tụ',
    'hùnghồ': 'hùng hổ',
    'bịnh đội': 'binh đội',
    'dng-nhất': 'đúng nhất',
    'gidi-quyét': 'giải-quyết',
    'phâi': 'phải',
    'giỗi-qugết': 'giải-quyết',
    'uấn- đề': 'vấn-đề',
    'nâm': 'nắm',
    'mac-dich': 'mục-đích',
    'Phấn nghĩa': 'Phản-nghĩa',
    'khinh -xuất': 'khinh-xuất',
    'bằn-chức': 'bổn-chức',
    'tổ thêm': 'tỏ thêm',
    'kim-chi ngoc-diép': 'kim-chi ngọc-diệp',
    'zã-tắc': 'xã-tắc',
    'bách tỉnh': 'bách tính',
    'kiêu-cố': 'kiên-cố',
    'nồi dai-bäc': 'nổi đại-bác',
    'vdng ngọc': 'vàng ngọc',
    'biệnluận': 'biện-luận',
    'nghỉ rằng': 'nghĩ rằng',
    'mäy may': 'mảy may',
    'Täm thực': 'Tầm thực',
    'đả rõ': 'đã rõ',
    'hòa hoắn': 'hòa hoãn',
    'binh qugền': 'binh quyền',
    'Hoàngthân': 'Hoàng-thân',
    'Cơ-Mật': 'Cơ-mật',
    'hoàngthành': 'hoàng-thành',
    'Phụ-chánh': 'Phụ-chính',
    'bai nước': 'hai nước',
    'tờ lờirất': 'một lời rất',
    'quí quốc': 'quý quốc',
    'nối lời': 'nói lời',
    'Co-Mậtviện': 'Cơ-mật-viện',
    'Thông-tông': 'Thống-tướng',
    'Thải-Hòa': 'Thái-Hòa',
    'tùy tông': 'tùy tùng',
    'tặng phầm': 'tặng phẩm',
    'Tèm thực': 'Tầm thực',
    'hốihả': 'hối hả',
    'Tham-biên': 'Tham-biện',
    'Son phỏng': 'Sơn-phòng',
    'mật-thảm': 'mật-thám',
    'cố ÿ': 'cố ý',
    'miễn cưởng': 'miễn cưỡng',
    'bạỏ-hành': 'bạo-hành',
    'đự-định': 'dự-định',
    'hỏa - hoãn': 'hòa-hoãn',
    'rỗi oậu': 'rồi sao',
    'Thäi-Nguyên': 'Thái-Nguyên',
    'Tuyên-quang': 'Tuyên-quang',
    'Vo sinh': 'Võ-sinh',
    'tinh-thông vũ-nghệ': 'tinh-thông võ-nghệ',
    'tuyềnmộ': 'tuyển-mộ',
    'Hồ-Oai': 'Hùng-Oai',  # Actually Kiểm-duyệt
    'Hùng - Duệ': 'Hùng-Duệ',
    'tượng-bỉnh': 'tượng-binh',
    'dư-đẩ': 'dư-dật',
    'chi-huy': 'chỉ-huy',
    'Trän-xuân-Soan': 'Trần-xuân-Soạn',
    'Trấn-Bình-Đài': 'Trấn-Bình-Đài',
    'khầu thần-công': 'khẩu thần-công',
    'Co-mât-viên': 'Cơ-mật-viên',
    'khai hổa': 'khai hỏa',
    'chỈ-huy': 'chỉ-huy',
    'diéukhièn': 'điều-khiển',
    'trọng-phảo': 'trọng-pháo',
    'cüng': 'cũng',
    'lui gi': 'lùi giờ',
    'vọng-lâu': 'vọng-lâu',
    'nổi hiệu': 'nổi hiệu',
    'Thốngtưởng': 'Thống-tướng',
    'thi-uy': 'thị-uy',
    'Sü-quän': 'Sứ-quán',
    'sï-quan': 'sĩ-quan',
    'man bảo': 'mạn báo',
    'đại- bác': 'đại-bác',
    'đữ-dội': 'dữ-dội',
    'Mang-Cà': 'Mang-Cá',
    'bất ngò': 'bất ngờ',
    'bổ chạy': 'bỏ chạy',
    'vü-khi': 'vũ-khí',
    'ngäp': 'ngáp',
    'gäy': 'gãy',
    'thai chân': 'hai chân',
    'hoäng-hôt': 'hoảng-hốt',
    'phòngthủ': 'phòng-thủ',
    'đồ đất': 'đổ đất',
    'lấp chận': 'lấp chặn',
    'Viét-quân': 'Việt-quân',
    'chuyền họng': 'chuyển họng',
    'phóng - thích': 'phóng-thích',
    'trùngdrục': 'trùng trục',
    'sụp đồ': 'sụp đổ',
    'bất đầu': 'bắt đầu',
    'phẩn-công': 'phản-công',
    'Häi-phông': 'Hải-phòng',
    'hàng ngû': 'hàng ngũ',
    'chiến-ham': 'chiến-hạm',
    'ảnh lửa': 'ánh lửa',
    'Niệc- Nam': 'Việt-Nam',
    'bất kề': 'bất kỳ',
    'cơ-cấu': 'cơ-cấu',
    'quânsy': 'quân-sự',
    'nhà ca': 'nhà của',
    'tan rä': 'tan rã',
    'cỗ dai-bâc': 'cỗ đại-bác',
    'dai-phäo': 'đại-pháo',
    'bộ Hinh': 'bộ Binh',
    'triét-thoäi': 'triệt-thoái',
    'giây lưng': 'dây lưng',
    'dinhthy': 'dinh thự',
    'ướclượng': 'ước-lượng',
    'vữ-khí': 'vũ-khí',
    'bị trọngthương': 'bị trọng-thương',
    'Mặc đầu': 'Mặc dầu',
    'khen ngọi': 'khen ngợi',
    'non nói': 'non nớt',
    'ái-qnốc': 'ái-quốc',
    'chuän-bi': 'chuẩn-bị',
    'minh-chứng': 'minh-chứng',
    'thựcdân': 'thực-dân',
    'đồngliêu': 'đồng-liêu',
    'tuyêt-ddi': 'tuyệt-đối',
    'hiều lầm': 'hiểu lầm',
    'nhận - định': 'nhận-định',
    '7hành Thuận - hóa': 'Thành Thuận-Hóa',
    'thất - thủ': 'thất-thủ',
    'Qui-müi': 'Quý-Mùi',
    'khôiphục': 'khôi-phục',
    'it ra': 'ít ra',
    'kể địch': 'kẻ địch',
    'lịch-ssử': 'lịch-sử',
    'phong -trào': 'phong-trào',
    'thời dé': 'thời dễ',
    'đàn-ảp': 'đàn-áp',
    'đảơ': 'đảo',
    'kỷ': 'ký',
    'đứng đắn': 'đúng đắn',
    'sôi nỗi': 'sôi nổi',
    'nhỗ': 'nhỏ',
    'thủ lổi': 'thủy lợi',
    'giặc nhô': 'giặc nhỏ',
    'chứcvụ': 'chức vụ',
    'đốt chính-trị': 'dốt chính-trị',
    'nung-nấu đầu:óc': 'nung-nấu đầu óc',
    'chiếnlược': 'chiến-lược',
    'Vinh-Yèn': 'Vĩnh-Yên',
    'mờ - mờ': 'mờ mờ',
    'Á-Rập': 'Ả-Rập',
    # Fix numbering
    '2#—': '2.—',
    '244': '24',
}

for old, new in ocr_fixes.items():
    text = text.replace(old, new)

# Normalize multiple blank lines
text = re.sub(r'\n{4,}', '\n\n\n', text)

# Fix spaces before punctuation
text = re.sub(r'\s+([,;:.!?])', r'\1', text)

with open(OUTPUT, 'w') as f:
    f.write(text)

print(f"Cleaned: {INPUT} -> {OUTPUT}")
lines = [l for l in text.split('\n') if l.strip()]
print(f"Non-blank lines: {len(lines)}")
