#!/usr/bin/env python3
"""
Second-pass cleaning for Chapter II VSTB Volume 6.
Targets remaining OCR errors, line-break artifacts, and formatting.
"""
import re
import sys

def clean_pass2(text: str) -> str:
    # 1. Fix merged titles
    text = text.replace('TỪ HUẾ RA TÂNSỞC', 'TỪ HUẾ RA TÂN-SỞ')
    
    # 2. Fix common Vietnamese OCR errors
    replacements = {
        # Missing/merged words
        'gần nữa không': 'gần như không',
        'gần nữa': 'gần như',
        'cỏ đánh': 'có đánh',
        'cỏ đâu': 'có đâu',
        'đẩ núng': 'đã núng',
        'bímật': 'bí-mật',
        'thấtbại': 'thất-bại',
        'bát-binh': 'bất-bình',
        'Tä-quän': 'Tả-quân',
        'thời - gian': 'thời-gian',
        'thảoo-luận': 'thảo-luận',
        'Ngựđạo': 'Ngự-đạo',
        'tỉnh sương': 'tinh sương',
        'dưởi': 'dưới',
        'độtngột': 'đột-ngột',
        'bước lèn': 'bước lên',
        'loan-giá': 'loan-giá',  # actually "Long-giá"?
        'khóc tòng': 'khóc ròng',
        'Thi-lang': 'Thị-lang',
        'thét mäng': 'thét mắng',
        'vừa đầy': 'vừa rày',
        'lâm sự,y': 'lâm sự đã',
        'đó ÿ': 'đã ý',
        'cy-ny': 'trách-nhủ',
        'hồng nhiều điềm': 'hỏng nhiều việc',
        'trong oạch': 'trong cuộc',
        'bỏng - bảy': 'bóng-bảy',
        'còn ngb': 'còn ngút',
        'gặt khói Ka': 'ngất khói lửa',
        'nhà th': 'nhà thờ',
        'Giảm-Mục': 'Giám-Mục',
        'Giám-Mục': 'Giám-Mục',
        'buồi tối': 'buổi tối',
        'đe Coury': 'de Courcy',
        'Thương bạcviện': 'Thương-bạc viện',
        'Đại-úy Sehmờitz': 'Đại-úy Schmitz',
        'toản lính': 'toán lính',
        'thảong': 'tháng',
        'lựclượng': 'lực-lượng',
        'khánghiến': 'kháng-chiến',
        'Hoàngthân': 'Hoàng-thân',
        'liếp-tục': 'tiếp-tục',
        'thưởng lệ': 'thường lệ',
        'bản tüyên-ngôn': 'bản tuyên-ngôn',
        'Kế tiếp ngày 97': 'Kế tiếp ngày 9-7',
        'vi6t thư': 'viết thư',
        'VạnNiên': 'Vạn-Niên',
        'két-quà': 'kết-quả',
        'Hàm - Nghỉ': 'Hàm-Nghi',
        'Muôn tda Bệ-hg': 'Muôn tâu Bệ-hạ',
        'Thün uừa': 'Thần vừa',
        'dién-vän': 'điện-văn',
        'Bệ. Hạ': 'Bệ-hạ',
        'cüng trở': 'cùng trở',
        'UỀ': 'về',
        'mội lượt': 'một lượt',
        'bề nghỉ': 'về nghỉ',
        'hiêm-cung': 'Khiêm-cung',
        'Tồng Tư-Lệnh': 'Tổng Tư-lệnh',
        'Kỷ tên': 'Ký tên',
        'Tôi lường': 'Tôi tường',
        '@ÑA ông': 'của ông',
        'Tòa Khảm': 'Tòa Khâm',
        'T\n\n-Thuyết': 'Tôn-Thất-Thuyết',
        'Tài liệu dưới': 'Tài-liệu dưới',
        '(ty về Huế': '(trở về Huế',
        'đo lệnh': 'do lệnh',
        'phâi': 'phải',
        '1h nào': 'lẽ nào',
        'dong điệu': 'giọng điệu',
        'khän-thiét': 'khẩn-thiết',
        'sỏn nién-thiéa': 'sớm niên-thiếu',
        'oà': 'và',
        'da nạn': 'đa nạn',
        'kề ziết': 'kể xiết',
        'Ngàp nay': 'Ngày nay',
        'oào': 'vào',
        'sào': 'vào',
        'hữa nghị': 'hữu nghị',
        'vâg': 'vậy',
        'bỗ': 'bỏ',
        'Phu-chinh': 'Phụ-chính',
        'Phu-chänh dai-thn': 'Phụ-chính đại-thần',
        'xửng đảng': 'xứng đáng',
        'hếi': 'hết',
        'Thién-dja': 'Thiên-địa',
        'ngó sào': 'ngó vào',
        'Trẫm họ': 'Trẫm với',
        'vói': 'với',
        'họa din': 'hòa dịu',
        'pững': 'vững',
        'huụnh-đệ': 'huynh-đệ',
        'củng': 'cùng',
        'xê': 'xẻ',
        'oui buồn': 'vui buồn',
        'đụng': 'đừng',
        'uĩ-lực': 'vũ-lực',
        'đối phô uởi nhau': 'đối phó với nhau',
        'ước-oọng nàp': 'ước-vọng này',
        'nề Kinh-kỳ': 'về Kinh-kỳ',
        'chầu hầu': 'chầu hầu',
        'Cỏn viée': 'Còn việc',
        'zin üy': 'xin ủy',
        'lắng mờiễu': 'lăng miếu',
        'uà': 'và',
        'Hoàng-gia': 'Hoàng-gia',
        'vi': 'vì',
        'côn': 'còn',
        'nàg': 'nay',
        'lui ngày': 'lùi ngày',
        'Quẳng-trị': 'Quảng-Trị',
        'còn quả': 'còn quá',
        'còn ': 'còn ',
        'xúc-phạm,': 'xúc-phạm.',
        'Kinhthanh': 'Kinh-thành',
        'so-xuất': 'sơ-xuất',
        'Nam-quân': 'Nam-quân',
        'vội-vÄ': 'vội-vã',
        'bẩy giờ': 'bảy giờ',
        'rưởi': 'rưỡi',
        'ngả': 'ngã',
        'áo-não': 'ảo-não',
        'phất-phởi': 'phất-phới',
        'KỊ đài': 'Kỳ đài',
        'đốt phả vì': 'đốt phá và',
        'củ': 'của',
        'của Ông': 'của ông',
        'Nhị dân': 'Nhân dân',
        'còi thoi-thóp': 'còn thoi-thóp',
        'Tron| cung': 'Trong cung',
        'mâm vàng đường kính dài năn': 'mâm vàng đường kính dài năm',
        'säu tấc': 'sáu tấc',
        'thừa -của': 'thừa của',
        'không được đi, cất': 'không được dời cất',
        'träm': 'trăm',
        'nguyà vẹn': 'nguyên vẹn',
        'thổi vàn': 'thoi vàng',
        'bạc đề': 'bạc để',
        'bảo - vật': 'bảo-vật',
        'qúy giả': 'quý giá',
        'tưởngtượng': 'tưởng-tượng',
        'phú': 'phù',  # context: "cho phú quân lính" -> "cho phù"
        'tự-do cướp phá': 'tự do cướp phá',
        'đồn hồ': 'đồng hồ',
        'đửa': 'đứa',
        'cải túi ảo quần': 'cái túi áo quần',
        'đỏ': 'đó',
        'cử thành': 'cửa thành',
        'dọn đẹp': 'dọn dẹp',
        'tử-th': 'tử-thi',
        'thải binh': 'tàn binh',
        'đảnh': 'đánh',
        'tiết xa': 'tiến xa',
        'thái.hậu': 'thái-hậu',
        'chại': 'chạy',
        'dục': 'thúc',
        'ngb': 'ngút',
        'gặt': 'ngất',
        'Tưởng': 'Tường',
        'Nguyễn văn Tưởng': 'Nguyễn-Văn-Tường',
        'th Kim-long': 'thờ Kim-long',
        'Giảm-Mục': 'Giám-Mục',
        'Văn-hóa Nguyêt-San': 'Văn-hóa Nguyệt-San',
        'chánh-trị': 'chánh-trị',
        'se Coury': 'de Courcy',
        'Tổng Trú sứ': 'Tổng-trú-sứ',
        'Hai ngày hôm sau (tức là vào hôm 13-7) de Courcy cũng': 'Hai ngày hôm sau (tức là vào hôm 13-7) de Courcy cũng',
        'đồ tố cáo': 'để tố cáo',
        'Kháng-chiến': 'kháng-chiến',
        'lắng vua Tự Đức': 'lăng vua Tự-Đức',
        'Còn các quan': 'còn các quan',
        'thảy đều': 'thảy đều',
        'TânSở': 'Tân-sở',
        'tình-thể cấp-bách': 'tình-thế cấp-bách',
        'nảo-động': 'náo-động',
        'vỗ-về': 'vỗ-về',
        'đưa ta': 'đưa ra',
        'quê quản': 'quê quán',
        'dé dàng': 'dễ dàng',
        'trải lại': 'trái lại',
        'binhM': 'binh-lính',
        'cấm -túc': 'cấm-túc',
        'gi gạo tồi': 'để gạo tới',
        'lèn đường': 'lên đường',
        'chỉ -thị': 'chỉ-thị',
        'Nhàanước': 'nhà-nước',
        'da.số': 'đa số',
        'đại- bác': 'đại-bác',
        'linh': 'lính',
        'chiến-khu': 'chiến-khu',
        'Quảng-- Trị': 'Quảng-Trị',
        'đã trở nên': 'đã trở nên',
        'cây bài chánh-trị': 'cây bài chính-trị',
        'moi': 'mới',
        'thi-hành': 'thi-hành',
        'Triều-đình hợp- cách': 'triều-đình hợp-cách',
        'xuấtbôn': 'xuất-bôn',
        'diền ấy': 'việc ấy',
        'al': 'ai',
        'khôný': 'không',
        'chối cäi': 'chối cãi',
        'øượt': 'vượt',
        'cwong-giéi': 'cương-giới',
        'hẹp-hỏi': 'hẹp-hòi',
        '#1': '',
        'san': 'sau',
        'rẮc -rối uô': 'rắc-rối vô',
        'củng vi': 'cùng vì',
        'xung - đột đồ': 'xung-đột đó',
        'biến đồi': 'biến-đổi',
        'thời-cục': 'thời-cục',
        'Vị vuatré': 'Vị vua trẻ',
        'rời khỗi': 'rời khỏi',
        'côn cỏ': 'còn có',
        'Chánh-phủ': 'chánh-phủ',
        'chánh-qnuền': 'chánh-quyền',
        'cỏn có ai': 'còn có ai',
        'có thề': 'có thể',
        'điềunước liếm': 'điều-ước liễm',
        'kÿ kết': 'ký kết',
        'uởi': 'với',
        'ngắn trở': 'ngăn trở',
        'chién-khu': 'chiến-khu',
        'Pao-ngw': 'Ngự-đạo',
        'Ống chỉ còn đặn': 'Ông chỉ còn dặn',
        'Tuần- phủ': 'Tuần-phủ',
        'chớ nghe Tưởng': 'chớ nghe Tường',
        'giữ nồi': 'giữ nổi',
        'ti-du viên': 'tri-huyện viên',
        'Phủ-thừa': 'phủ-thừa',
        'thượngthư': 'Thượng-thư',
        'Thịlang': 'Thị-lang',
        'bộ Hinh': 'bộ Hình',
        'phô': 'phò',
        'đau lòng này': 'đau lòng này',
        'từ-giã': 'từ-giã',
        'dé': 'để',
        'tra lệ': 'trào lệ',
        'từng chém': 'từng chém',
        'ngoänh mặt': 'ngoảnh mặt',
        'mùng 66-1881': 'mùng 6-6-1884',
        'Hoàngphải': 'Hoàng-phái',
        'ˆthân-thần': 'thân-thần',
        'phụ họa': 'phụ họa',
        'VỀ Huể': 'Về Huế',
        'cải nguc-thảot': 'cái ngục-thất',
        'quản-đội Phúp': 'quân-đội Pháp',
        'kê dịch': 'kẻ địch',
        'hôa-binh': 'hòa-bình',
        'sỡ': 'sẽ',
        'bổ giang-son': 'bỏ giang-sơn',
        'ca tiën-trièu': 'của tiên-triều',
        'đầu công': 'đã từng',  # actually maybe "đã từ công"
        'cỏn có lội': 'còn có lỗi',
        'hậu-thể': 'hậu-thế',
        'mờiếu-zũ': 'miếu-tổ',
        'uề': 'về',
        'nữaa': 'nữa',
        'côn': 'còn',
        'liệt - thánh': 'liệt-thánh',
        'hoäng-tnyën': 'hoàng-tuyền',
        'Vän-Xà': 'Văn-Xá',
        'chiếu cần vương': 'chiếu Cần-vương',
        'sỉ-dân': 'sĩ-dân',
        'xung-dôt': 'xung-đột',
        'thựcdân': 'thực-dân',
        'bithiét': 'bi-thiết',
        'kichthich': 'kích-thích',
        'gọn-gàng': 'gọn-gàng',
        'bổng': 'bóng',
        'phổ - biến': 'phổ-biến',
        'toàn - quốc': 'toàn-quốc',
        'vüa': 'vua',
        'uiệc': 'việc',
        'thề': 'thể',
        'hỏa': 'hòa',
        'giặc đôi': 'giặc đòi',
        'chưa có co': 'chưa có cơ',
        'uậu': 'vậy',
        'bäl-déc-di': 'bá-lược chi',
        'phẩi': 'phải',
        'Tháiđương': 'Thái-Dương',
        'đất Kỳ': 'đất Kỳ',
        'HuyỀn-lỏng': 'Huyền-Vũ',
        'đấi': 'đất',
        'Thục': 'Thục',
        'oiệc': 'việc',
        'tir': 'từ',
        'đổ có': 'đã có',
        'đa - đoan': 'đa-đoan',
        'tré tuồi': 'trẻ tuổi',
        'lự chủ': 'tự chủ',
        'mél ngang ngạnh': 'mỗi ngang ngạnh',
        'chänh-tinh': 'chánh-tình',
        'bối rối uô 0ùng': 'bối rối vô cùng',
        'chủng': 'chúng',
        'bình thuyền': 'binh thuyền',
        'thỀ': 'thể',
        'Rinh-thành': 'Kinh-thành',
        'sập đốn': 'sập đổ',
        'Rẻ': 'Kẻ',
        'khôug': 'không',
        'bdo-vé': 'bảo-vệ',
        'dã': 'đã',
        'dän-do hai diều': 'đắn đo hai điều',
        '1': 'một',
        'oào': 'vào',
        'đối phỏ': 'đối phó',
        'naụ': 'nay',
        'dồề': 'để',
        'oỀ tươnglai': 'về tương-lai',
        'lhôiih® œui nên dy': 'thời thế xui nên vậy',
        'củng chia': 'cùng chia',
        'mối io nàụ': 'mối lo này',
        'di biết': 'đã biết',
        'nghièn răng': 'nghiến răng',
        'giác': 'giặc',
        'VẢ lại': 'Vả lại',
        'nghĩadé': 'nghĩa-đế',
        'dâu': 'đâu',
        'kín': 'xưa',
        'nậu': 'vậy',
        'mông': 'mỏng',
        'gắp': 'gặp',
        'biến-cổ': 'biến-cố',
        'A thành': 'Kinh-thành',  # might be "Kinh thành"
        'xa-giá': 'xa-giá',
        'xấn-hồ': 'xấu-hổ',
        'chi có': 'chỉ có',
        'luân-lÿ': 'luân-lý',
        'uới': 'với',
        'kề lớn nhô': 'kể lớn nhỏ',
        'bô': 'bỏ',
        'Rẻ trí': 'Kẻ trí',
        'người dũng': 'người dũng',
        'cé.': 'có',
        'bỗ': 'bỏ',
        'chớ nề': 'chớ nề',
        'nguy-hièm': 'nguy-hiểm',
        'chống đồ': 'chống đỡ',
        'truânchuyên': 'truân-chuyên',
        'kiền-bách': 'kiền-bách',
        'ngổ-hầu': 'ngõ hầu',
        'chuyền loạn thành trị': 'chuyển loạn thành trị',
        'ngng': 'ngừng',
        'ra gền': 'ra yên',
        'ấu': 'ấy',
        'lôn-zä': 'long-gia',
        'dản': 'dân',
        'củng lo véi nhan': 'cùng lo với nhau',
        'nghĩ véi nhau': 'nghĩ với nhau',
        'hé chẳng tốt lắm ru': 'há chẳng tốt lắm ru',
        'lỏng': 'lòng',
        'mượn cé tránh ra': 'mượn cớ tránh ra',
        'di linh': 'đi lính',
        'trọng nghĩa cửu-cấp': 'trọng nghĩa cứu-cấp',
        'viéc công': 'việc công',
        'kể sĩ': 'kẻ sĩ',
        'bỗ': 'bỏ',
        'väo chã tối': 'vào chỗ tối',
        'vi.': 'vì',
        'sống thừa ở trên đời': 'sống thừa ở trên đời',
        'thân áo mũ': 'thân áo mũ',
        'lảm trâu ngựa': 'làm trâu ngựa',
        'điền-hình': 'điển-hình',
        'hẳn-hoi': 'hẳn-hòi',
        'chở đề': 'chớ để',
        'nghiém-so': 'nghiêm-sớ',
        'tuén theo': 'tuân theo',
        'hâm thử': 'hãm thử',  # or "Hãm thử"? probably "Hãm thử" is incorrect
        'hưởng-ứng': 'hưởng-ứng',
        'CaoBằng': 'Cao-Bằng',
        'sơn cùng thủy tận': 'sơn cùng thủy tận',
        'trich-uc': 'trích-ục',
        'phụng Dụ': 'phụng Dụ',
        'trong lược': 'trong lược',
        'phẩm-nhã!': 'phẩm-nhã',
        'phâm': 'phàm',
        'cảm thù': 'cảm thù',
        'Cam-lộ hộ - giá': 'Cam-lộ hộ-giá',
        'khôi-aghïa': 'khởi-nghĩa',
        'tiéu-diét': 'tiêu-diệt',
        'tôn phủ quổc-tộ': 'tôn phù quốc-tộ',
        'cử oiệc': 'cứ việc',
        'tủy tâm, tủy sức': 'tùy tâm, tùy sức',
        'Triền-đình': 'Triều-đình',
        'thànhđiền': 'thành-điền',
        'Du': 'Dụ',
        'hưởng-ửng': 'hưởng-ứng',
        'dé-nhi-nièn': 'đệ-nhị-niên',
        'phụng sao': 'phụng sao',
        'tò chiếu': 'tờ chiếu',
        'khai - phục ngu': 'khai-phục nguyên',
        'họ Hoàng': 'họ Hoàng',
        'Giápthân': 'Giáp-thân',
        'Tiếtghế': 'Tiết-chế',
        'quânvụ đạithần': 'quân-vụ đại-thần',
        'đồng chí': 'đồng-chí',
        'xử': 'xử',
        'Tông đốc': 'Tổng đốc',
        'Sơn-Hưng': 'Sơn-Hưng',
        'Nguyễn-đìnhNhuận': 'Nguyễn-Đình-Nhuận',
        'Hiép-thông': 'Hiệp-thống',
        'quân-vu dai-thảon': 'quân-vụ đại-thần',
        'thăng thụ Tuän-phü': 'thăng thụ Tuần-phủ',
        'Lang-Binh': 'Lạng-Binh',
        'Tông-thông': 'Tổng-thống',
        'Nguyễn-vănNhư': 'Nguyễn-Văn-Như',
        'Nguyễn-văn-Giáp': 'Nguyễn-Văn-Giáp',
        'NguyễnCao': 'Nguyễn-Văn-Cao',  # or just Nguyễn-Cao
        'Nguyễn-Thiện': 'Nguyễn-Thiện',
        'Vũ-Giốc': 'Vũ-Giác',
        'Ngô-quang-Huy': 'Ngô-Quang-Huy',
        'Hoàng-đình-Kính': 'Hoàng-Đình-Kính',
        'efng': 'cùng',
        'khai phục': 'khai phục',
        'phô-bién': 'phổ-biến',
        'Nguyén-quang-Bich': 'Nguyễn-Quang-Bích',
        'Bắc-Kinh': 'Bắc-Kinh',
        '(lẾp-viện': '(cầu-viện',
        'bai hịch': 'bài hịch',
        'Nam-kÿ': 'Nam-kỳ',
        'độtkích': 'đột-kích',
        '“üthai': 'bức-hại',  # OCR artifact
        'hoảnghốt': 'hoảng-hốt',
        'ba van quân': 'ba vạn quân',
        'rước': 'với',  # context: "với tình thế"
        'khần-trương': 'khẩn-trương',
        'lựclượng khả mạnh': 'lực-lượng có thể mạnh',
        'đổi phó nồi': 'đối phó nổi',
        'triệt-binh': 'triệt-binh',
        'đồn hết': 'dồn hết',
        'quânđội': 'quân-đội',
        'Trung-kÿ': 'Trung-kỳ',
        'Trungkÿ': 'Trung-kỳ',
        'mờiền HồngLam': 'miền Hồng-Lam',
        'nôt': 'nốt',
        'l&ch-nhiệm': 'trách-nhiệm',
        'Thống tưởng': 'Thống tướng',
        'Mt': 'mất',
        'tranh-däu': 'tranh-đấu',
        'dân-tộc ViệtNam': 'dân-tộc Việt-Nam',
        "'ường": 'Tường',
        'ra thú': 'ra thú',
        '(WẪ gỡ': 'đã gỡ',
        'hiệu-triệu': 'hiệu-triệu',
        'đã ————': 'đã phải ký',
        'đjiiwng-lích': 'Quang-Bích',
        'Nguyễn-quan ch': 'Nguyễn-Quang-Bích',
        'Me nây': 'vì này',  # context: maybe "bởi này"
        'Thanh-đình': 'Thanh-đình',
        'thäi-dé': 'thái-độ',
        'sắp đột trân': 'sắp đặt trên',
        'bề ngoài': 'bề ngoài',
        'Hàm: ì': 'Hàm-Nghi',
        'tài-hện minh-chứng': 'tài-liệu minh-chứng',
        'phải ký đề kêu gọi': 'phải ký để kêu gọi',
        'Khäng-chién': 'kháng-chiến',
        'toàn. quốc': 'toàn quốc',
        'han-dinh': 'hạn-định',
        'Kháng chiến': 'kháng-chiến',
        'phiến-loạn': 'phiến-loạn',
        'cáo-thị': 'cáo-thị',
        'giải-tán': 'giải-tán',
        'khai thác -triệt.đề': 'khai thác triệt-để',
        'dù muốn dù không': 'dù muốn dù không',
        'công-cu': 'công-cụ',
        'Đế-quốc': 'Đế-quốc',
        'Tân-sở ?': 'Tân-sở?',
        'Cao-nguyên': 'cao-nguyên',
        'khô-khan': 'khô-khan',
        'cô': 'có',
        'địađiềm': 'địa-điểm',
        'LaoBảo': 'Lao-Bảo',
        'Mai-Linh': 'Mai-Linh',
        'huyên-ly': 'huyện-ly',
        'thượng đạo': 'thượng-đạo',
        'Hà-Tỉnh': 'Hà-Tĩnh',
        'Tânsổ': 'Tân-sở',
        'bi-mật': 'bí-mật',
        'Khängchiến': 'kháng-chiến',
        'Bắc -kỳ': 'Bắc-kỳ',
        'Cửa Việt': 'Cửa Việt',
        'Cam -lộ': 'Cam-lộ',
        'chung-quanh': 'chung-quanh',
        'lãm rảo': 'làm rào',
        'điện-tích': 'diện-tích',
        'mẫu tây': 'mẫu tây',
        'đài': 'dài',
        'thước tây': 'thước tây',
        'rông': 'rộng',
        'cớ': 'có',
        'Hành-. cung': 'Hành-cung',
        'lợithể': 'lợi-thế',
        'chiếnlược': 'chiến-lược',
        'huy-động': 'huy-động',
        'đảo hầm, đấp lũy': 'đào hầm, đắp lũy',
        'ngây': 'ngày',
        'vật-liệu': 'vật-liệu',
        'bạc tiền': 'bạc tiền',
        'Tôngtrü-st': 'Tổng-trú-sứ',
        'Tän-sô': 'Tân-sở',
        'ngạc -nhiên': 'ngạc-nhiên',
        'chối - cãi': 'chối-cãi',
        'Trúsứ': 'Trú-sứ',
        'thãm': 'thăm',
        'De Champeax': 'de Champeaux',
        'tẰng': 'rằng',
        'tháng 61885': 'tháng 6-1885',
        'tri-giâ': 'trị-giá',
        'chuyền nất': 'chuyển nốt',
        'nộivụ': 'nội-vụ',
        'quần Pháp': 'quân Pháp',
        'thảonh-nôi': 'thành-nội',
        'vo-vét': 'vo-vét',
        'hàng trắm\' hòm': 'hàng trăm hòm',
        'đấc công': 'đắc công',
        'đóng vai đấc công và\nNgày nay': 'đóng vai đắc công. Ngày nay',
        'Wào': 'Vào',
        'vién-binh': 'viện-binh',
        'tới i64': 'tới lẻ tẻ',
        'Án-sát': 'Án-sát',
        'vôi-vä': 'vội-vã',
        'Vô-trong-Binh': 'Võ-Trọng-Bình',
        'Vô-trong-Binh': 'Võ-Trọng-Bình',
        'mặc đầu': 'mặc dầu',
        'vua.ông': 'vua, ông',
        'đòi hổi': 'đòi hỏi',
        'Phạm-thậnDuât': 'Phạm-Thận-Duật',
        'tiếtlộ': 'tiết-lộ',
        'Tuän-vü': 'Tuần-vũ',
        'HôHiền': 'Hồ-Hiền',
        'rời bô': 'rời bỏ',
        'Hàn-Nghi': 'Hàm-Nghi',
        'Kinh- (hành': 'Kinh-thành',
        'Hai ống': 'Hai ông',
        'Tôn-thất Thuyết': 'Tôn-Thất-Thuyết',
        'mỉnh': 'mình',
        '50 TỪ HUẾ RÀ TÂN-SỞ': '',  # remove this running header artifact
        'đân': 'dân',
        'xử-trị': 'xử-trị',
        'manh-tâm': 'manh-tâm',
        'nao-núng tỉnh thần': 'nao-núng tinh-thần',
        'vấtvả': 'vất-vả',
        'Giáo-sĩ': 'Giáo-sĩ',
        'Phé-länh-binh': 'Phó-lãnh-binh',
        'rải-rác': 'rải-rác',
        'thứ-thiếp': 'thứ-thiếp',
        'di': 'đi',
        'Nghé-an': 'Nghệ-an',
        'xuyên sơn': 'xuyên sơn',
        'Điềm': 'Điềm',
        'Bäng-son': 'Bảng-sơn',
        'Bảngsơn': 'Bảng-sơn',
        'Cam-lộ': 'Cam-lộ',
        'vậtlực': 'vật-lực',
        'hănghái': 'hăng-hái',
        'sở-dĩ bỏ': 'sở-dĩ bỏ',
        'đâyông': 'đây ông',
        'Cam-Lộ': 'Cam-lộ',
        'trù-phú': 'trù-phú',
        'Ngòài': 'Ngoài',
        'Cam-lô': 'Cam-lộ',
        'sẻ': 'sẽ',
        'cải túi': 'cái túi',
        'biền': 'biển',
        'bế tắc nốt': 'bế tắc nốt',
        'nguy-hiềm': 'nguy-hiểm',
        'trong-phäo': 'trong-pháo',
        'ÿ-kiến': 'ý-kiến',
        'xui giục': 'xui giục',
        'di Nghệ. Tĩnh': 'đi Nghệ-Tĩnh',
        'lâu đài': 'lâu dài',
        'Đạo-ngựg': 'Đạo-ngự',
        'Bến-Đuối': 'Bến-Đuối',
        '{ Ngoài': '(Ngoài',
        'khổi': 'khỏi',
        'CồnTiên': 'Cồn-Tiên',
        'hgày': 'ngày',
        'tän mác': 'tản mác',
        'thực-phầm': 'thực-phẩm',
        'cüng': 'cũng',
        'thiết quân-luật': 'thiết-quân luật',
        'cấm đân chứng': 'cấm dân chúng',
        'phân ngay gian': 'phân ngay gian',
        'aivi': 'ai vi',
        'đề ché kêu': 'để chó kêu',
        'chuyền quân': 'chuyển quân',
        'bí-mật chịu tử hình': 'bí-mật chịu tử hình',
        '|': '',
        'Bảo-đài': 'Bảo-đài',
        'hâu-dao': 'hậu-đạo',
        'đồngtình': 'đồng tình',
        'Ăn cắp': 'ăn cắp',
        'Lai-cäch': 'Lai-cách',
        'thám-tử': 'thám-tử',
        'mờiền Bắc': 'miền Bắc',
        'Đồng-Hới': 'Đồng-Hới',
        'hạm-đội': 'hạm-đội',
        'pháo-thuyền': 'pháo-thuyền',
        'Thanh-Nghệ-Tỉnh': 'Thanh-Nghệ-Tĩnh',
        'BắcKỷ': 'Bắc-kỳ',
        'ĐồngHới': 'Đồng-Hới',
        'viện đạn': 'viên đạn',
        'bô đi': 'bỏ đi',
        'triệtthoái': 'triệt-thoái',
        'Thủy-bathượng': 'Thủy-ba thượng',
        'trắng gốc- gác': 'trắng gốc gác',
        'đào ngữ': 'đào ngũ',
        'VUA HÀM-NGHÀ': 'VUA HÀM-NGHI',
        'QUA AI- LAO': 'QUA AI-LAO',
        'xà': 'và',
        'Bái-trời': 'Bái-trời',  # actually could be "Bài-trời" or "Bái Trời"
        'Ở Tân-sở': 'ở Tân-sở',
        'Tri-phủ': 'Tri-phủ',
        'Ngữu-cước': 'Ngữu-cước',
        'Sau tây': 'Sau này',
        'kề trên': 'kể trên',
        'Vô-trong-Binh': 'Võ-Trọng-Bình',  # re-verify
        'Nam- định': 'Nam-Định',
        'đám giữ': 'dám giữ',
        'e mang họa': 'e mang họa',
        '257': '25-7',
        'kiëm-dièm': 'kiểm-điểm',
        'tèn': 'tên',
        'Phän-nghïa': 'Phấn-nghĩa',
        'phảobinh': 'pháo-binh',
        'Mại-lĩnh': 'Mai-lĩnh',
        'bổ lại': 'bỏ lại',
        'rùng rậm um-tüm': 'rừng rậm um-tùm',
        'đường xả': 'đường xá',
        'ngách': 'ngách',
        'người Mọi': 'người Mọi',
        'kiếm lai vãng': 'kiếm lai vãng',  # or "đi lại vãng"
        'nhữug': 'những',
        'thác nước chẩy siết': 'thác nước chảy siết',
        'nôi bọt trắng phau': 'nổi bọt trắng phau',
        'nguy-hiềểm': 'nguy-hiểm',
        'đóng bè': 'đóng bè',
        'Đạo-ngự có bữa': 'Đạo-ngự có bữa',
        'Âm-wôt': 'âm-ướt',
        'tê-liệt': 'tê-liệt',
        'bổ lại': 'bỏ lại',
        'lều quán': 'lều quán',
        'bèn đường': 'bên đường',
        'vùi qua loa': 'vùi qua loa',
        'đua nhau': 'đua nhau',
        'Mai -lộ': 'Mai-lộ',
        'Bang\nMai': 'Bang-Mai',
        'Đan-sơn': 'Đan-sơn',
        'da ra ngăn': 'đã ra ngăn',
        'đốt sạch': 'đốt sạch',
        'Ngô-tất-Ninh': 'Ngô-Tất-Ninh',  # maybe Ngô Tất Ninh
        'Biệnlý Thể': 'Biện-lý Thể',
        'Triphủ': 'Tri-phủ',
        'Triệu Phong': 'Triệu Phong',
        'hăng hải': 'hăng hái',
        '247-1885': '24-7-1885',
        'lính ổ Huế': 'lính ở Huế',
        'Tônthất-Thuyết': 'Tôn-Thất-Thuyết',
        'kếo': 'kéo',
        'Tânsở': 'Tân-sở',
        'cấp tốc': 'cấp tốc',
        'Mai-lĩnh': 'Mai-lĩnh',
        'Phó lãnh-binh': 'Phó lãnh-binh',
        'gập': 'gặp',
        'Ngữu-ước': 'Ngữu-cước',
        'Tuầnvũ': 'Tuần-vũ',
        'lựclượng tương-đương': 'lực-lượng tương-đương',
        'Tả-quân Lượng': 'Tả-quân Lượng',
        'đi bất vua': 'đi bắt vua',
        'Ham-nghi': 'Hàm-Nghi',
        'giảo mác': 'giáo mác',
        'mang theò': 'mang theo',
        'khầu': 'khẩu',
        'Tä-quân Lượng': 'Tả-quân Lượng',
        'Vụng-kho': 'Vụng-kho',
        'de Courey': 'de Courcy',
        'nghỉ': 'nghi',
        'trường-hợp': 'trường-hợp',
        'it lâu': 'ít lâu',
        'Hương-Hóa tùng giờ': 'Hương-Hóa đúng giờ',
        'hợp sức': 'hợp sức',
        'bièn-gioi': 'biên-giới',
        'Việtgian': 'Việt-gian',
        'gìn giữ': 'gìn giữ',
        'cùng đường': 'cùng đường',
        'giết vua Häm-nghi': 'giết vua Hàm-Nghi',
        'đuôi theo': 'đuổi theo',
        'Bạng-Câu': 'Bạng-Câu',
        'làng Mọi': 'làng Mọi',
        'Đôi bên': 'Đôi bên',
        'giỗi': 'giỏi',
        'bắn vo ta 1': 'bắn vào ta!',
        'chuần bị': 'chuẩn bị',
        'mệt nhọc': 'mệt nhọc',
        'yếu thế': 'yếu thế',
        'rút lui': 'rút lui',
        'nguy-quân': 'nguy-quân',
        'Mä-Hạc': 'Mã-Hạc',
        'Cửu-châu': 'Cửu-châu',
        'ngồi trên voi': 'ngồi trên voi',
        'Trương - quang-Đẩn': 'Trương-Quang-Đản',
        'gần tới nơi': 'gần tới nơi',
        'Y phải': 'Y phải',  # maybe "Y bảo"?
        'đi tắt': 'đi tắt',
        'đỏn đầu': 'đón đầu',
        'quânMỸ': 'quân-sĩ',
        'sốt rét': 'sốt rét',
        'gần đủ mặt': 'gần đủ mặt',
        'Cửn-Châu': 'Cửu-Châu',
        'dû': 'đủ',
        'mướn': 'mướn',
        'điền-chủ': 'điền-chủ',
        'bị bắn hết': 'bị bắn hết',
        'Bản Ta-Ba-Chon': 'Bản Ta-Ba-Chon',
        'điềm cực Nam': 'điểm cực Nam',
        'Cammon': 'Cammon',
        'ly-sở': 'lỵ-sở',
        'Thakhet': 'Thakhek',
        'Ïnh': 'tỉnh',
        'Savannakhet': 'Savannakhet',
        'Qui hop': 'Quy-hợp',
        'Cam-Cúc': 'Cam-Cúc',
        'SơnPhòng': 'Sơn-Phòng',
        '(Œ) Ngợ-đạo': '(1) Ngự-đạo',
        'sông Khone': 'sông Khone',
        'Mường Tehépone': 'Mường Thépone',
        'Mường Vang': 'Mường Vang',
        'Mường Mahaxay': 'Mường Mahaxay',
        'phẩi lữu lạt': 'phải lưu lạc',
        'Ban Tong': 'Bản Tổng',
        'phia Bông-Bắc': 'phía Đông-Bắc',
        'trunglâm-điềm': 'trung-tâm điểm',
        'ba tồng Ban, Tong, Phon Savan': 'ba tổng Ban, Tổng, Phon Savan',
        'Ban-na-Thot': 'Ban-na-Thot',
        'Ÿ đây': 'ở đây',
        'tích. tực': 'tích-cực',
        'ng-hộ': 'ủng-hộ',
        'cụ Phan-dinh-Phüng': 'cụ Phan-Đình-Phùng',
        'sông Nai': 'sông Nai',
        'à': 'là',
        'lách qua khe núi': 'lách qua khe núi',
        'chẩy': 'chảy',
        'sông Gianh': 'sông Gianh',
        'Unh': 'tỉnh',
        'bầy': 'bảy',
        'nghïa-düng': 'nghĩa-dũng',
        'cù-mục': 'mục',  # or "cựu mục"
        'Cai-Mân': 'Cai-Mân',
        'Thanh-hỏa': 'Thanh-Hóa',
        'kết nạp': 'kết nạp',
        'lính Tàu': 'lính Tàu',
        'xã Ngọc-Lâu': 'xã Ngọc-Lâu',
        'Ninh-Bình': 'Ninh-Bình',
        '500 quân': '500 quân',
        'gây.ra': 'gây ra',
        'Trường-sơn': 'Trường-sơn',
        'đèo Quy-Hợp': 'đèo Quy-Hợp',
        'Nguyễn-Chánh': 'Nguyễn-Chánh',
        'Tôổng:đốc': 'Tổng-đốc',
        'Nghệ-an': 'Nghệ-an',
        'ChỈ-huy': 'Chỉ-huy',
        'Sơn-phòng': 'Sơn-phòng',
        'Hà-tĩnh': 'Hà-tĩnh',
        'hầu cận': 'hầu cận',
        'Phanđình-Phùng': 'Phan-Đình-Phùng',
        'đồng-chí': 'đồng-chí',
        'hoạt-động': 'hoạt-động',
        'Nghệ-an': 'Nghệ-an',
        'Hà-nh': 'Hà-Tĩnh',  # context
        'Lê-Ninh': 'Lê-Ninh',
        'Bố-chảnh': 'Bố-chánh',
        'Lê-Kiên': 'Lê-Kiên',
        'La-sơn': 'La-sơn',
        'lãnhđạo': 'lãnh-đạo',
        'văn-thân': 'văn-thân',
        'dân-chúng': 'dân-chúng',
        'chiếm tỉnhthành': 'chiếm tỉnh-thành',
        'Hà-tỉnh': 'Hà-tĩnh',
        'Lê-Đại': 'Lê-Đại',
        'Trịnh-văn-Báu': 'Trịnh-Văn-Báu',
        'phong-trèào': 'phong-trào',
        'ảiquốc': 'ái-quốc',
        'manh-më': 'mạnh-mẽ',
        'xich-mờich': 'xích-mích',
        'cánhân': 'cá-nhân',
        'hay giữa': 'hay giai-cấp',  # or "hay giữa các"
        'đồng-bào Kinh, Thượng': 'đồng-bào Kinh, Thượng',
        'xung đột lương, giao': 'xung-đột lương, giáo',
        'cà': 'cả',
        'phe đẳng': 'phe đảng',
        'phù Lê': 'phù Lê',
        'phù Nguyễn': 'phù Nguyễn',
        'đoàn-kết': 'đoàn-kết',
        'thống-nhất hành-động': 'thống-nhất hành-động',
        'đĩ-nhiên': 'đĩ-nhiên',
        'giờ phút đỏ': 'giờ phút đó',
        'cái: đầu': 'cái đầu',
        'Hình-Bộ Thượngthư': 'Hình-bộ Thượng-thư',
        'triệt-để': 'triệt-để',
        'chỉ-thị': 'chỉ-thị',
        'tân-triều': 'tân-triều',
        # Remaining page header artifacts
        '40 TỪ HUẾ RA TẢN-SỞ': '',
        '42 TỪ HUẾ RA TẢN-SỞ': '',
        '44 TỪ HUẾ RA TẢN-SỞ': '',
        '46 TỪ HUẾ RA TẢN-SỞ': '',
        '48 TỪ HUẾ RA TẢN-SỞ': '',
        '50 TỪ HUẾ RA TẢN-SỞ': '',
        '52 VUA HÀM-NGHI QUA AI-LAO': '',
        '54 VUA HÀM-NGHI QUA AI-LAO': '',
    }
    
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    # Fix remaining hyphenated line breaks that got missed
    text = re.sub(r'(\w)-\s+(\w)', r'\1\2', text)
    text = re.sub(r'(\w)-\n(\w)', r'\1\2', text)
    
    # Fix excessive spaces
    text = re.sub(r'  +', ' ', text)
    
    # Fix spaces before punctuation
    text = re.sub(r'\s+\.', '.', text)
    text = re.sub(r'\s+,', ',', text)
    text = re.sub(r'\s+;', ';', text)
    text = re.sub(r'\s+:', ':', text)
    
    # Fix quotes spacing
    text = re.sub(r'«\s+', '« ', text)
    text = re.sub(r'\s+»', ' »', text)
    
    # Fix empty lines after removing running headers
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = re.sub(r'\n{2,}(?=\n)', '\n', text)
    
    # Remove trailing spaces from lines
    lines = text.split('\n')
    lines = [l.rstrip() for l in lines]
    text = '\n'.join(lines)
    
    return text.strip()


def main():
    if len(sys.argv) != 3:
        print("Usage: clean_ch2_pass2.py <input_file> <output_file>")
        sys.exit(1)
    
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    
    with open(input_path, 'r', encoding='utf-8') as f:
        raw = f.read()
    
    cleaned = clean_pass2(raw)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(cleaned)
    
    print(f"Pass 2 cleaned text written to {output_path}")
    print(f"Input: {len(raw)} chars, Output: {len(cleaned)} chars")
    line_count = len(cleaned.split('\n'))
    print(f"Lines: {line_count}")


if __name__ == '__main__':
    main()
