#!/usr/bin/env python3
"""Reconstruct the classification output from the override dict (since batch_3.json was cleaned up)."""
import json, sys

# All 154 question IDs from the batch in order
qids = [
    "DABT-5092","DABT-5093","DABT-5094","DABT-5095","DABT-5096","DABT-5097","DABT-5098","DABT-5099","DABT-5100","DABT-5047",
    "DABT-5101","DABT-5102","DABT-5103","DABT-5104","DABT-5105","DABT-5106","DABT-5107","DABT-5108","DABT-5109","DABT-5110",
    "DABT-5048","DABT-5111","DABT-5112","DABT-5113","DABT-5114","DABT-5115","DABT-5116","DABT-5117","DABT-5118","DABT-5119",
    "DABT-5120","DABT-5049","DABT-5121","DABT-5122","DABT-5123","DABT-5124","DABT-5125","DABT-5126","DABT-5127","DABT-5128",
    "DABT-5129","DABT-5130","DABT-5131","DABT-5050","DABT-5132","DABT-5133","DABT-5134","DABT-5135","DABT-5136","DABT-5137",
    "DABT-5138","DABT-5139","DABT-5140","DABT-5141","DABT-5143","DABT-5152","DABT-5242","DABT-5153","DABT-5154","DABT-5155",
    "DABT-5156","DABT-5157","DABT-5158","DABT-5159","DABT-5160","DABT-5161","DABT-5144","DABT-5162","DABT-5163","DABT-5164",
    "DABT-5165","DABT-5166","DABT-5167","DABT-5168","DABT-5169","DABT-5170","DABT-5171","DABT-5145","DABT-5172","DABT-5173",
    "DABT-5174","DABT-5175","DABT-5176","DABT-5177","DABT-5178","DABT-5179","DABT-5180","DABT-5181","DABT-5146","DABT-5182",
    "DABT-5183","DABT-5184","DABT-5185","DABT-5186","DABT-5187","DABT-5188","DABT-5189","DABT-5190","DABT-5191","DABT-5147",
    "DABT-5192","DABT-5193","DABT-5194","DABT-5195","DABT-5196","DABT-5197","DABT-5198","DABT-5199","DABT-5200","DABT-5201",
    "DABT-5148","DABT-5202","DABT-5203","DABT-5204","DABT-5205","DABT-5206","DABT-5207","DABT-5208","DABT-5209","DABT-5210",
    "DABT-5211","DABT-5149","DABT-5212","DABT-5213","DABT-5214","DABT-5215","DABT-5216","DABT-5217","DABT-5218","DABT-5219",
    "DABT-5220","DABT-5221","DABT-5150","DABT-5222","DABT-5223","DABT-5224","DABT-5225","DABT-5226","DABT-5227","DABT-5228",
    "DABT-5229","DABT-5230","DABT-5231","DABT-5151","DABT-5232","DABT-5233","DABT-5234","DABT-5235","DABT-5236","DABT-5237",
    "DABT-5238","DABT-5239","DABT-5240","DABT-5241"
]

assert len(qids) == 154, f"Expected 154, got {len(qids)}"

overrides = {
    "DABT-5092":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "medium"},
    "DABT-5093":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "", "confidence": "medium"},
    "DABT-5094":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5095":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5096":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5097":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5098":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "medium"},
    "DABT-5099":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5100":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5047":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5101":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "medium"},
    "DABT-5102":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5103":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "high"},
    "DABT-5104":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "", "confidence": "high"},
    "DABT-5105":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "medium"},
    "DABT-5106":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "", "confidence": "medium"},
    "DABT-5107":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "", "confidence": "medium"},
    "DABT-5108":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "medium"},
    "DABT-5109":  {"domain": "Domain III", "sub_domain": "A.Hazard ID", "task": "", "confidence": "medium"},
    "DABT-5110":  {"domain": "Domain III", "sub_domain": "A.Hazard ID", "task": "", "confidence": "high"},
    "DABT-5048":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5111":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5112":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5113":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5114":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5115":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5116":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T1", "confidence": "high"},
    "DABT-5117":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5118":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5119":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5120":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5049":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5121":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5122":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5123":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "high"},
    "DABT-5124":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5125":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5126":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5127":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5128":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5129":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "medium"},
    "DABT-5130":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T1", "confidence": "high"},
    "DABT-5131":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T1", "confidence": "high"},
    "DABT-5050":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5132":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5133":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5134":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5135":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5136":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5137":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "medium"},
    "DABT-5138":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5139":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5140":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5141":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5143":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5152":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "high"},
    "DABT-5242":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5153":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "high"},
    "DABT-5154":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5155":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5156":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5157":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5158":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5159":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5160":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5161":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5144":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5162":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5163":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5164":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5165":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5166":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5167":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5168":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5169":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5170":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5171":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "high"},
    "DABT-5145":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "high"},
    "DABT-5172":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "medium"},
    "DABT-5173":  {"domain": "Domain I", "sub_domain": "A.Design", "task": "", "confidence": "high"},
    "DABT-5174":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5175":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5176":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5177":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5178":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5179":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5180":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5181":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5146":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "high"},
    "DABT-5182":  {"domain": "Domain I", "sub_domain": "B.Execute", "task": "", "confidence": "high"},
    "DABT-5183":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5184":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5185":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5186":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5187":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5188":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5189":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5190":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5191":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5147":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5192":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T8", "confidence": "high"},
    "DABT-5193":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5194":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "medium"},
    "DABT-5195":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T1", "confidence": "high"},
    "DABT-5196":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T1", "confidence": "high"},
    "DABT-5197":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5198":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5199":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5200":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5201":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5148":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "medium"},
    "DABT-5202":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5203":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5204":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5205":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5206":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5207":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5208":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5209":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5210":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5211":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5149":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T9", "confidence": "high"},
    "DABT-5212":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5213":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5214":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5215":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5216":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5217":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5218":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5219":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5220":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5221":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5150":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5222":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5223":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5224":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5225":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5226":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5227":  {"domain": "Domain III", "sub_domain": "A.Hazard ID", "task": "", "confidence": "high"},
    "DABT-5228":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5229":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5230":  {"domain": "Domain III", "sub_domain": "B.Exposure", "task": "", "confidence": "high"},
    "DABT-5231":  {"domain": "Domain III", "sub_domain": "C.Dose-Response", "task": "", "confidence": "high"},
    "DABT-5151":  {"domain": "Domain I", "sub_domain": "C.Interpret", "task": "", "confidence": "high"},
    "DABT-5232":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5233":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T3", "confidence": "high"},
    "DABT-5234":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T3", "confidence": "high"},
    "DABT-5235":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
    "DABT-5236":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T3", "confidence": "high"},
    "DABT-5237":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "high"},
    "DABT-5238":  {"domain": "Domain IV", "sub_domain": "Applied", "task": "T7", "confidence": "high"},
    "DABT-5239":  {"domain": "Domain II", "sub_domain": "Mechanistic", "task": "T4", "confidence": "high"},
    "DABT-5240":  {"domain": "Domain III", "sub_domain": "B.Exposure", "task": "", "confidence": "high"},
    "DABT-5241":  {"domain": "Domain III", "sub_domain": "D.RiskChar&Mgmt", "task": "", "confidence": "high"},
}

# Verify all IDs are covered
missing = [qid for qid in qids if qid not in overrides]
assert not missing, f"Missing overrides for: {missing}"

# Build output in order
output = []
for qid in qids:
    r = overrides[qid]
    output.append({
        "question_id": qid,
        "domain": r["domain"],
        "sub_domain": r["sub_domain"],
        "task": r["task"],
        "confidence": r["confidence"]
    })

# Statistics
from collections import Counter
domains = Counter(q["domain"] for q in output)
confs = Counter(q["confidence"] for q in output)
print(f"Total: {len(output)} questions", file=sys.stderr)
print(f"Domains: {dict(domains)}", file=sys.stderr)
print(f"Confidence: {dict(confs)}", file=sys.stderr)

# Output JSON array only (as specified)
print(json.dumps(output, indent=2))
