#!/usr/bin/env python3
"""Translate ch5-clean.txt into English with scholarly Burckhardtian voice."""

# The translation follows these critical rules:
# - ALL Vietnamese proper names preserved, NEVER translated
# - Both lunar AND Western dates preserved
# - Dialogue rendered colloquially/raw (preserve emotional register)
# - Author's footnotes woven into narrative
# - NO translator footnotes, NO commentary, NO interpretation
# - Titles on first use: translate with VN in parentheses, then English

with open('/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch5-clean.txt', 'r') as f:
    vn = f.read()

# Build the translation by processing the VN text
# The translation is structured as a complete English rendering

translation = """CHAPTER V

THE CAN VUONG MOVEMENT AFTER KING HAM NGHI'S EDICT
[Original: PHONG-TRÀO CẦN-VƯƠNG SAU LỜI HỊCH CỦA VUA HÀM-NGHI]

KING HAM NGHI'S ACTIVITIES IN HA TINH
[Original: VUA HÀM-NGHI HOẠT-ĐỘNG Ở HÀ-TĨNH]

As we have seen, being blocked at Quang Binh, Mr. Thuyet was compelled to take the Ai-lao (Laos) route to bring the king to Bac Ky, intending to establish additional operational bases. The Royal Procession (Ngự-đạo) followed the western side of the Truong Son range and proceeded until it reached Cửu Châu, belonging to the town of Savannakhet in Ai-lao. The Royal Procession halted here for three days, utterly exhausted. The weather in Ai-lao at that time, as in Trung Ky, was very trying. In the land of Laos it was then the rainy season — an incessant downpour all day and all night; by contrast, Vietnam was experiencing a season of heat that scorched the skin and burned the flesh. So heavy was the rain that rivers and streams overflowed, fields and lowlands were inundated, spawning much disease, principally fever. King Ham Nghi, unaccustomed to exposure and hardship, fell ill and had to lie in a hammock, carried by soldiers. Behind came four or five more hammocks bearing officials, ten horses and three elephants, fifty civilian porters hauling supplies, and two hundred soldiers and officers of all ranks attending the royal retinue.

The Châu-Mường (Lao District Chief) at Mahaxay, named Tong-Hom, having received secret word of the king's approach, hastily dispatched five functionaries to Ban Ta Pa Tion to welcome the Royal Procession, offering provisions, shelter, and lodging along the route the Procession would pass. The king, appreciating his goodwill, presented him with four horses and ten rifles. But after the rainy season, word of this reached the Siamese government (Chánh-phủ Tiêm-la), and he was summoned to Bangkok (Vọng-các) to pay a fine of 1,600 ticaux (then valued at 2,400 quan) and compelled to return the gifts he had received, for he had not requested permission from the royal court — note that at this time Ai-lao was still subject to the court of Bangkok (1).

(1) The Kingdom of Siam had long maintained a prohibition on the sale of elephants abroad.

According to Captain (Bại-úy) Gosselin, King Ham Nghi's itinerary passed through the following places:

"The first day, that is to say the 5th or 6th of August 1885 [5-6-8-1885], the Royal Procession halted at Ban Ta Pa Tion on the Nam Pha Nang River, a tributary of the Se Bang Fai River. The Royal Procession slept here.

"The second day the king slept at Ban Na Poung.

"The third and fourth days the king slept at Ban Na Sen.

"The fifth day the king slept at Ban Na Pong.

"The sixth day the king slept at Ban Soi.

"The seventh day the king slept at Ban Sok.

"The eighth day the king slept at Ban Tha Chou.

"The ninth day the king slept at Ban Bo, then crossed Mount Phu Ak. The tenth day the king slept directly on the mountain.

"The eleventh day the king slept in the forest beside the Nam An River.

"The twelfth day (approximately 18 August 1885) the king slept at Ban Tong."

While resting in these Lao villages, only the king and the officials had shelter from the rain and sun; as for the soldiers, they slept wherever they could, sprawled about in the stilt-houses, their clothing soaked and unable to dry, and their meals consisted of nothing more than a little broken rice or maize. At times night fell while they were still traveling on forest paths with no villages or hamlets in sight, and the soldiers had to cut trees and gather leaves to erect makeshift shelters for the king against the dew and wind. Encountering stretches of road that were muddy and waterlogged, they would have the elephants dip their trunks into the mire to test the depth, then construct rafts for the elephants to drag the entire party across. Elephants were invaluable in this period for crossing rivers sometimes over two meters deep, and for this reason Mr. Thuyet, wherever he found elephants for sale, would do his utmost to purchase them; but the court of Bangkok had strictly forbidden the sale of elephants out of the country without special government authorization. The purchase of elephants was thus extremely difficult and commanded very high prices.

Because the soldiers and coolies suffered from malaria and dysentery in great numbers, many deserted and many died, despite their efforts to seek physicians and medicines and to care for one another attentively. These pitiable dead upon the road of flight into the remote mountains and deep valleys included persons of every station, from mandarins to common soldiers, not even possessing a mandarin's robe to wrap their bodies. They were buried hastily and perfunctorily, and the survivors pressed on, fleeing from the enemy's claws. Later, upon returning to the Central region, the number of survivors did not exceed forty.

Crossing the Quy-hop Pass (the Quy-hop road being the sole route from Ai-lao into Ha Tinh) at the end of the 7th month (i.e., the end of August by the Solar calendar), King Ham Nghi reached Ham Thao, a Muong territory seven days' travel from the Son Phong headquarters in Ha Tinh. The Son Phong mandarin, Nguyen Chanh, dispatched Captain (Suất-đội) Cao Dat with a number of soldiers to meet him; thus the Royal Procession was greatly reinforced (1). Mr. Thuyet's plan was to make this region a base for restoration. The provincial mandarin reported back to Hue; the Three Dowager Empresses (Tam-cung) greatly rejoiced and sent Ton That Phan as Imperial Commissioner (Khâm-sai) with 350 soldiers of Ha Tinh province and a Military Commander (Lãnh-binh) to escort the king. By the 5th of September [5-9], King Ham Nghi had recovered somewhat from his exhaustion, but upon arrival he received news that the French had deposed him and installed his elder brother Mệ Trìu upon the throne. King Đồng Khánh and Lady Tu Du had issued an Edict (Dụ) both condemning the Resistance and calling for its surrender one more time.

At the Son Phong headquarters in Ha Tinh, the mandarins and notables, hearing of the king's arrival, thronged to pay their respects. Mr. Thuyet proceeded to reorganize many matters: recruiting righteous volunteer soldiers (nghĩa-dũng), establishing relay stations and fortifications at strategic points, and appointing officials: the former Supernumerary Gentleman (Viên-ngoại-lang) Phan Quang Cu as Finance Commissioner (Bố-chánh) of Ha Tinh; the former Surveillance Commissioner (Án-sát) Huỳnh Xuan Phong as Mountain Pacification Commissioner (Sơn-phòng-sứ); the former Prefect (Tri-phủ) Ngụy Khac Kieu as his deputy; the former Prefect Phan Khac Hoa as Surveillance Commissioner of Ha Tinh; the former Imperial Inspector (Đô-ngự-sử) Phan Đình Phùng as Advisor (Tán-lý); and Phan Trọng Muu as Mountain Pacification Assistant (Sơn-phòng Tham-biện). But scarcely had these arrangements been provisionally calculated and implemented when word arrived that the French pursuers were approaching. At this juncture Mr. Thuyet drafted a second Can Vuong edict, using King Ham Nghi's words both to call the entire nation to Resistance once more and to answer the Edict of King Đồng Khánh described above. This Edict (Chiếu) was dated the 11th day of the 8th lunar month (i.e., 20 September 1885 [20-9-1885]), the second year of Ham Nghi, issued immediately after the French had performed the coronation ceremony for King Đồng Khánh. In substance it said:

"France and our country signed a peace treaty several decades ago. At first, we ceded to France the three eastern provinces of Nam Ky; two years later they seized the remaining three western provinces. But their greed was still not satisfied. They then schemed to establish a Legation (Sứ-quán) in Hue and Consuls (Lãnh-sự) in Bac Ky, applying pressure to force us constantly to amend this clause and alter that article — who knows how many times. Finally they resolved to seize Bac Ky, the infinitely precious inheritance of our ancestors. Then, at the time of King Duc Tong's [Tự Đức's] passing, French troops stormed Thuan An gate, burning even the imperial seal that China had conferred upon our kings. They further demanded to station troops within the Imperial Citadel, training large cannon on our vital positions, and openly intimidated the Court, so that soldiers and people alike could no longer endure it.

"In the 5th month just past, the French brought over ten thousand men to compel us to surrender the Imperial City and execute their commands. The Privy Council (Cơ-mật-viện) was therefore obliged to launch an attack at the Capital. If we won, Nguyễn Văn Tường was to come out to welcome Us — at that time We would temporarily withdraw to Nghe An — while Ton That Thuyet would remain in the Capital to fight the French and exterminate the Catholics who had colluded with the enemy against the Court. If We lost, We would go with the court officials to the North to plan for restoration.

"The attack on the French was launched on the 3rd of the 5th month; by half-past eight the following morning it was over. The enemy dead were so numerous they could not be evacuated; their losses were also beyond counting. This was Heaven's doing, which none could avoid.

"At that very moment Nguyễn Văn Tường, following... [text corrupt]... the Capital, but unexpectedly he changed his allegiance and fled into the church... Ton That Thuyet never left Our side.

"We reached Quang Tri, and the French sent Tuong to summon Us back to return the Imperial City. That was a trick, a deception. From now on, Tuong has sided with the enemy, deceiving the people, plotting to capture Us and hand Us over to the French in pursuit of riches and honors — a crime as weighty as Heaven itself... Tuong even forged the handwriting of the Empress Dowager (Thái-hậu) to lure Us back, but the Empress Dowager is at this time in the hands of the French; Tuong could have her write whatever he wished. Yet according to the Testament of the late Emperor, women shall not meddle in affairs of state; therefore, if anyone comes into possession of that Edict, they should burn it and speak of it no more — that is the best course.

"We are now at Au Son (Huong Khe) together with Ton That Thuyet. Let all mandarins come forward and join the Can Vuong enterprise (1)..."

(1) This letter is excerpted from the book "King Ham Nghi" by Phan Tran Chuc.

The above Edict of King Ham Nghi was a necessary response to correct and counter the accusations and calumnies of the pro-French Nam Trieu faction, who had thoroughly exploited King Đồng Khánh and Lady Tu Du.

On the 17th of October 1885 [17-10-1885], the Vice-Viceroy (Kinh-lược phó-sứ) of Bac Ky, Nguyễn Trọng Hợp, also issued a proclamation to the army and people, harmonizing with the Edicts of Lady Tu Du and King Đồng Khánh:

"Notwithstanding the Edicts which His Majesty and Her Majesty the Empress Dowager have already promulgated, I observe that many persons still heed the deceptions of the rebel faction (1). In recent years, our court has passed through many upheavals; a number of high ministers have usurped power, assassinating one king and installing another — truly a rebellion against Heaven and Earth. They have also exiled many members of the Imperial Clan and stained their hands with countless other grave crimes... King Ham Nghi, upon examination, had no right to participate in the succession; his having been elevated to the throne was merely the doing of two Regents (Phụ-chánh) who sought to satisfy their private interests, and they falsely spread the story that this was the intention of King Kien Phuc. Where is the evidence?

"As for the calamity that befell the Capital, it was entirely the work of Ton That Thuyet and Nguyễn Văn Tường. At first they were of one heart and one will with the rest; later, these men fell into discord, causing the Imperial Ancestral Temples to topple and the court to be endangered — like a frayed thread before a blade. Now Heaven, in its kindness, has protected the State through this crisis. The waves have subsided, the winds have calmed, &c. &c."

Needless to say, everyone understood that the above Edicts and proclamations were the work of French hirelings (tay-sai), embellished according to their masters' instructions and broadcast abroad to shatter the prestige of the Resistance. The Empress Dowager Tu Du, no less than King Đồng Khánh, was at that time nothing but a puppet of the Empire, and being in French hands, could naturally do no otherwise. But could the prestige of that puppet king and puppet Empress Dowager truly obscure the role of the Resistance? No! If France and its lackeys had succeeded in this, the Can Vuong movement could not possibly have lasted another twenty years. In other words, far from diminishing the authority of King Ham Nghi and Mr. Thuyet, the French only enhanced the stature of the Resistance leaders. Thus, when the Can Vuong edict reached the ears of all classes of our countrymen, the wave of patriotism and hatred for the Colonialists blazed up like fire. Throughout the entire nation, the notables and scholar-gentry zealously agitated for anti-French and anti-Catholic action (Binh Tay sat Ta — "Pacify the West, Kill the Leftists"). The voices of patriots from Nam to Bac completely drowned out the calls for peace and order issued by the political gangsters on the banks of the Perfume River. In Thua Thien alone, Nguyễn Văn Tường imposed martial law and terrorized the population, somewhat reducing the anti-French movement; but from Binh Thuan northward, disturbances erupted everywhere. Catholic and non-Catholic blood flooded through all the villages, most tragically. And simultaneously, in some places righteous volunteer armies were being recruited for the Resistance; in others, bandits rose up to fish in troubled waters; in yet others, mandarins were captured or killed; and elsewhere, scholar-gentry flocked to the Can Vuong banner — the situation, confused and chaotic, defied description.

THE UPRISINGS IN THE SOUTHERN CENTRAL REGION
[Original: NHỮNG VỤ KHỞI NGHĨA TẠI MIỀN NAM TRUNG-KỲ]

Readers will surely recall that since the Giap Tuat Treaty (1874) came into being, the Can Vuong and Van Than (Literati) movements had been set in motion. In Nghe An, the Bachelors (Tú-tài) Trần Tấn and Đặng Như Mai assembled the degree-holders of the region, circulated anti-French, anti-Catholic proclamations, and joined together to destroy many Catholic villages. Unable to withstand French repression, they allied with a group of righteous fighters (nghĩa-sĩ) who had armed forces at their command — such as Trần Quang Cần, Trương Quang Thủ, and Nguyễn Huy Điền — to attack the citadel of Ha Tinh and lay siege to Dien Chau district. Later, the Court dispatched Nguyễn Văn Tường as Imperial Commissioner (Khâm-sai) and Lê Ba Thận as Commander-in-Chief (Tổng-thống) to suppress them. This uprising began in the first month and was not extinguished until the sixth month of that year. The suppression of the anti-French Van Than was carried out by Tự Đức, who had just signed the peace treaty with France and therefore dared not tolerate any anti-French activities — a pattern we had already witnessed in Nam Ky over a decade earlier.

The Van Than uprising in Nghe-Tinh was temporarily pacified, but the mass movement continued covertly, especially after the Van Than saw that the anti-French faction had taken control of the Nam Trieu. The anti-French attitude of Mr. Thuyet's party became evident from the time of the French attack on Thuan An gate; they then established contact in order to respond to King Ham Nghi's call after the capital fell. From that point a new phase began.

In the 6th month of the At Dau year (1885), French troops arrived and stationed themselves at Dong Hoi; in the 7th month they occupied the citadel of Nghe; in the 8th month they took Quang Tri and Binh Dinh. The French probably did not station troops in Quang Tri because they knew that King Ham Nghi had already moved to Quang Binh, making a garrison at Quang Tri both useless and costly in manpower. A company of Zouaves (baggy-trousered soldiers) was dispatched to operate throughout the two provinces of Quang Nam and Quang Ngai.

In the 7th month of the Binh Tuat year (1886), the scholars of Binh Dinh province also stirred, but Nguyễn Thân suppressed them.

In the 10th and 11th months of that year, the Chief Mountain Pacification Officer (Chánh-sứ Sơn-phòng) Trần Văn Dự established a Righteous Society (Nghĩa-hội) and led his Righteous Army to besiege the provincial capital. The Provincial Governor (Tuần-Vũ), Nguyễn Ngoạn, the Finance Commissioner Bùi Tấn Quang, and the Surveillance Commissioner Hà Thúc Quán fled. Later, French troops recaptured the city, destroyed Trung Loc fort and the Mountain Pacification headquarters. Trần Văn Dự's Righteous Society disintegrated. He returned to the Capital to surrender, but as soon as he reached the provincial seat, the French arrested and executed him. The Phó-bảng (Deputy Scholar) Nguyễn... [name corrupt] had established a new administration at Trung Lap in Que Son district, where the Van Than had set up offices, residences, military camps, and even a Confucian temple (Văn-miếu) together with officials, in order to maintain their authority before the people.

In the 2nd month of the Binh Tuat year (1886), King Đồng Khánh sent Phan Thanh Liem (son of Phan Thanh Gian) as Imperial Commissioner to conciliate the notables. In the 5th month, Phan Thanh Liem was assigned to the two provinces of Thuan-Khanh as Governor-General (Tổng-đốc). The Surveillance Commissioner Nguyễn Đình Văn became Finance Commissioner of Binh Thuan; the former Provincial Governor of Binh Thuan, Võ Doãn Tuân, became Finance Commissioner of Khanh Hoa; the Censor (Ngự-sử) Nguyễn Văn Chất became Surveillance Commissioner of Khanh Hoa, etc. — all lower positions being left to the discretion of the provincial heads.

In Quang Nam at this time, the Righteous Army was weakening day by day. In the 6th month, Nguyễn Hiệu suffered a major defeat at An Lam mountain; many elders (cựu-mục) fell in battle; provisions, funds, and weapons were mostly confiscated by the enemy. A few months later, Nguyễn Thân captured Nguyễn Hiệu, put him in a cage, and sent him to the Capital. The head having been cut off, the Resistance in Quang Nam was from that moment annihilated; the notables gradually came forth to surrender.

In the 3rd month of the following year (Đinh Hợi — 1887), the French reinforced the forces of the Imperial Commissioner of the Phan family and of the Nghia-Dinh Pacification and Recruitment Commissioner (chiêu-thảo-sứ) of the Nguyễn family with two companies of European troops and one company of native auxiliaries, each company 200 men strong, in order to finish the pacification quickly.

By the 7th month of the Đinh Hợi year, from Quang Nam south to Binh Thuan relative peace and order had been restored, so the Nam Trieu sent Nguyễn Thuật as Tả Trực kỳ Commissioner (Tả-trực kỷ) and Propaganda Commissioner (Tuyên-ủy) to deal with the high officials and to instruct the people of the two aforementioned provinces.

The pacification from Quang Binh northward to Bac Ky was far more difficult for the French colonialists. King Ham Nghi continued to move between Quang Binh and Nghe-Tinh; the Can Vuong party in this region was stronger, further impelling the scholar-commoner uprisings in Quang Nam and Quang Ngai. In the 5th month, the Nam Trieu, seeing the futility of conciliation, agreed with the French to adopt more resolute measures against the Righteous Army. Thus Nguyễn Thân was appointed Nghia-Dinh Pacification and Recruitment Commissioner (Nghĩa-Định chiêu-thảo-sứ) for Quang Ngai and Binh Dinh, as we have seen. After three months, Nguyễn Thân employed every conceivable brutal method, killing and arresting the populace without sparing even infants or old men, shattering countless families, so that the Righteous Army lost all its popular support. By the end of the 7th month of that year, Nguyễn Thân had succeeded.

In the provinces of Binh Thuan, Khanh Hoa, and Phu Yen, Trần Bá Lộc, Lieutenant De Lorme, and Administrator (Trù-sự) Aymonier were also dispatched by the Governor of Nam Ky to conduct suppression; these men established a wide communication network, supporting each other closely and efficiently. Trần Bá Lộc employed the most savage methods — so much so that even his French advisors were horrified (see Viet Su Tan Bien, Volume V) — but secretly the French were delighted that the strategy of "capping the well and killing" had proved so terribly effective. In the intercalary 4th month of the Đinh Hợi year, Trần Bá Lộc captured the Provincial Graduate (Cử-nhân) Mai Xuân Thuong and Bùi Điền, who were the Garrison Commander (Thống Trấn) and Deputy General (Phó-tướng) of the Righteous Army, together with eleven other elders (cựu-mục), and had them all executed in order to terrorize the local uprising movement.

In Phu Yen, the Righteous Army rose up and captured the province, taking the Finance Commissioner Phạm Như Xương prisoner. The Surveillance Commissioner Huỳnh Côn and the Military Commander Nguyễn Văn Hanh escaped. The French brought troops and warships and quickly recaptured the province; then the Nam Trieu sent the Left Assistant of the Finance Ministry (Tả-lý bộ Hộ), Lương Xuân Huyền, and the Reader of the Inner Cabinet (Thị-độc Nội-các), Cao Đệ, to restore order and the administrative apparatus. Huyền assumed the post of Finance Commissioner, Đệ that of Surveillance Commissioner.

The four southern provinces having been pacified, Trần Bá Lộc fined the notables of the region 180,000 đồng to cover military expenses. In the 4th month, King Đồng Khánh reorganized the administrative machinery in the Central region: Tôn Thất Bá became Finance Commissioner; the former Surveillance Commissioner Đinh Duy Tân retained his former post; and the district and sub-district offices and various agencies were left for these men to fill as they saw fit.

During this period, the revolutionaries Phan Đình Phùng, Tống Duy Tân, and Cao Điền also established Huong Khe and Hung Linh as their operational bases for the anti-enemy struggle from 1885 to 1895.

We shall present a clear account of several notable battles in later chapters as examples of the heroic struggle of the Vietnamese race. Even our adversaries themselves admired these acts of resistance.

As for the uprisings in the southern part of Trung Ky, we deeply regret that we lack sufficient historical materials, because the national history records of the righteous cause are very sketchy. In truth, from Lang Son to Ha Tien, the scholar-gentry and people all rose up to respond to King Ham Nghi's call — the only difference was that some regions were stronger and others weaker. That the uprisings from Quang Nam and Quang Ngai southward did not last as long as the movement in northern Trung Ky was due to less favorable geographical and economic conditions.

BATTLES IN THE NORTHERN CENTRAL REGION
[Original: NHỮNG TRẬN ĐÁNH TẠI MIỀN BẮC TRUNG-KỲ]

How Did De Courcy Pursue King Ham Nghi?
[Original: De-Courcy đuổi theo vua Hàm-Nghi thế nào?]

In July 1885, French troops occupied Dong Hoi to block King Ham Nghi's route to the North. In August of that year, Colonel Chaumont led a battalion and three warships from Da Nang into the Lam River and captured the provincial capital of Nghe An. But they held only the citadel; the mandarins and the people had all fled. If a few remained, they acted as double agents, so the French dared not fully trust them.

The Resistance of that time had already learned to apply the scorched-earth policy (vườn không nhà trống) and non-cooperation with the enemy; they even placed their own networks within enemy territory. The enraged enemy resorted only to massacring the population, burning pagodas and temples, and recruiting their fellow Catholic countrymen as puppet soldiers (nguy-binh) and informants (chỉ-điểm).

On 10 September 1885, Major Roy conducted an inspection at Quang Tri, deployed troops for occupation, re-established the Cho Sai market, and called upon the populace to return to trade and commerce to revive economic activity. On the 3rd and 4th of October, Captain Dallier arrived to relieve the An Ninh Seminary at Cua Tung. There, 4,000 Catholics had since 8 September been heroically resisting the siege of the Righteous Army. On 12 October, Dallier's forces were dispatched to Bai Son, where 200 Catholics had just been massacred the previous day. More than a thousand Catholics who had taken refuge inside the Quang Tri citadel survived (1).

(1) It is estimated that in less than a year and a half, up to 40,000 Catholics were killed, 48 French missionaries and over 40 Vietnamese priests (Linh-mục) lost their lives, and 9,000 churches were burned — losses amounting to millions in silver. It should be recalled that the Catholic-non-Catholic conflict had begun 60 years earlier; now, driven by patriotism, the slaughter proceeded more fiercely than ever. At that time, everyone was prejudiced that all Catholics followed the French. In truth, only a few priests and missionaries sided with the colonialists, dragging along a certain number of their flock. But when the Resistance meted out punishment, the wheat and the chaff were mingled together, and no distinction could be made between the honest and the guilty. Consequently, many Catholics, however unwilling, were forced to flee to the French for protection. Had the anti-Catholic campaign been pursued as a deliberate policy, could it have given rise to such internecine strife — brother against brother — while the anti-French front might have counted many Catholic soldiers among its ranks? But hasty and ill-considered decisions drove a great number of our countrymen into the enemy's camp. Regrettable indeed! This error rests clearly upon the Resistance and cannot be shifted onto anyone else.

On 22 October 1885, Captain Petit led a company of light infantry to Quang Tri, then proceeded to inspect Cam Lo, Tan So, and Mai Linh. French troops burned the Righteous Army's gunpowder depot at Tan So, capturing and killing forty combatants. Petit returned to Quang Tri on 4 November 1885. It should also be noted that the French deployed African soldiers to pacify the southern part of Trung Ky from 5 October 1885 to the end of that year, because the Righteous Army there was rising up in succession. At the end of 1885, the French established a telegraph line to facilitate military communications from Quang Nam to Hue.

Around the 10th month of the At Dau year (26 November 1885), the Resistance killed 600 Catholics from the two villages of Tho Ninh and Đinh Truong in Đuc Tho district, Nghe An province. Father Satre, who had taken refuge with the Catholics on this occasion, was struck by three bullets from the Resistance and died of his wounds. At that time, Major Grégoire's forces were ordered to pursue and drive off the Resistance. These forces, however, having slaughtered the populace so excessively, achieved no notable results. Major-General Prudhomme himself complained of this. Being hotly pursued by Pelletier's troops, the Resistance withdrew southward and by mid-November 1885 went into hiding at Bai Đuc and Cua Ve (in the Gianh River basin and at the confluence of the Rao Nay and Rao Nan rivers). During this period, the French forces held no consultations among themselves and did not coordinate their efforts, rendering many operations fruitless.

In February 1886, the enemy occupied Ha Tinh province and established bases at Cho Đon and at the mouth of the Gianh River. At this time, the anti-French struggle of our compatriots in Bac Ky was also greatly troubling the enemy, although the enemy had as many as 30,000 troops scattered everywhere. The enemy was compelled to withdraw the forces then operating in Trung Ky to the North at the beginning of March 1886.

This development forced them to abandon many positions in the three provinces of Nghe, Tinh, and Binh, retaining only a defensive hold at the mouth of the Gianh River. Seeing the French transferring troops from the Central region to reinforce the North, the court of Đồng Khánh was extremely alarmed.

To steady the spirits of the puppet king and his court, and on the recommendation of Father Hoang, the colonialists organized a "Northern Tour" (Bắc Tuần) for Đồng Khánh in the summer, while simultaneously establishing puppet troops under the banner of the Nam Trieu and dispatching a number of French soldiers as an escort. On the journey from Hue to Quang Tri and Quang Binh, the Righteous Army repeatedly launched surprise attacks against the Royal Procession. After two weeks of ineffective activity — and perhaps also for security reasons — the French had King Đồng Khánh return to the Capital by steamship on the 7th day of the 8th month. The French made yet another attempt at a cunning scheme: they urged King Đồng Khánh to issue an Edict conferring upon King Ham Nghi the title of Governor-General (Tổng-trấn) of the three provinces of Thanh Hoa, Nghe An, and Ha Tinh, hoping to exploit the prestige of the resistance king to calm the seeds of rebellion in those regions, which were seething with anti-French sentiment. On this occasion, Paul Bert also instructed the Nam Trieu to restore the former rank of the Imperial Son-in-Law (Phó-mã) Hoàng Tá Viêm and appoint him as Pacification Commissioner for the Right Direct Circuit (Hữu-trực-kỳ Yên-phủ Kinh-lược sứ) (1). The restoration of Hoàng Tá Viêm's former titles was a shrewd maneuver by the French colonialists. Why? Because Hoàng Tá Viêm had long been renowned as a patriotic soldier, a steadfast Can Vuong leader who had previously rendered many anti-French achievements in Bac Ky; he still commanded the sympathies of the scholar-gentry throughout the nation. By putting him forward as a decoy, would the Resistance not be thrown into doubt? When Hoàng set out, Đồng Khánh had already issued the Edict conferring the aforementioned title upon King Ham Nghi; former officials such as Trương Văn Ban, Nguyễn Trực, Nguyễn Chữ, Lê Mộ Giai, Nguyễn Nguyên Thành, Phan Trọng Mưu, Nguyễn Xuân Ôn, Lê Doãn Nha, and Ngô Xuân Quýnh were also restored to their former ranks and permitted to serve as officials from Quang Binh and Quang Tri southward. As for the cases of Trần Xuân Soạn, Phan Đình Phùng, and Nguyễn Phạm Tuân, if they agreed to submit, they would also be pardoned and granted other ranks, except for Lê Thuyết [Tôn Thất Thuyết], who could not be re-employed but would be spared prosecution.

(1) The "Right Direct Circuit" (Hữu-trực) comprised Quang Tri and Quang Binh; the "Right Circuit" (Hữu-kỳ) comprised Ha Tinh, Nghe An, and Thanh Hoa.

In the 10th month of the Binh Tuat year (i.e., November 1886), Hoàng Tá Viêm (1) led 300 native auxiliaries to Quang Binh and commenced pacification overtures, but only a few insignificant persons surrendered, among them Phạm Văn Mỹ, a former employee of the Privy Council who had earlier sought to serve King Ham Nghi after the Can Vuong army withdrew from the citadel of Ha Tinh. He had been listed among the close attendants. Now, seeing that the Resistance had no future, Phạm Văn Mỹ surrendered to Hoàng Tá Viêm. Viêm sent Mỹ up to Minh Cam for Captain Boulangier to employ. At this time, King Ham Nghi was constantly on the move; Mỹ informed the French to seek out Trương Quang Ngọc, who was close to the king, in order to carry out the plan to capture him.

At that time, the French had not established many strongpoints along the national highway. Communication from one strongpoint to another was extremely difficult because the Resistance ambushed constantly; the French had to provide military escorts for their mandarin collaborators before they dared to travel. These collaborators managed the administration but were obliged to keep their headquarters immediately adjacent to French posts. Occasionally they crept into neighboring villages to conscript porters and soldiers, only to be captured or killed themselves.

From Quang Khe to Ha Tinh, or from Quang Khe to Dong Hoi, the enemy had to deploy many troops just to move about. General (Đề-đốc) Lê Trực commanded here. His base was situated on the Gianh River in the Thanh Thuy region. It was a forward position from which soldiers could be dispatched into both Quang Binh and Ha Tinh provinces.

For us as for the French, the center of the Resistance at that time remained Quang Binh and Ha Tinh. Both sides exerted tremendous effort in this region.

In early 1886, the enemy was besieged so tightly by the Resistance at Dong Hoi that they were confined to the defensive, not daring to venture out of the citadel. The enemy had to send Captain Carnot with troops to relieve them. It can be said that the French situation at that time was very dark and perplexing.

And viewing the overall picture, we see that the French suppression effort throughout the Central region from the end of 1885 to the end of 1886 was not very successful; moreover, the uprising movements in Bac Ky were also very persistent and fierce. For technical reasons, we shall address these in the second part of this book.

Addendum (Chú thích). — According to the testimony of one of our mandarins given to the commander of Dong Hoi province, and of the Military Graduate (Võ-cử) Nguyễn Viết Tôn at Thanh Hoa, the following details were revealed:

Seven or eight months after leaving the Capital, King Ham Nghi and his followers were still skulking around Quang Binh in the northern direction. The pursuing French troops picked up the king's hammock and Mr. Thuyet's horse. The king's provisions were gradually exhausted; even the 170 chests of silver entrusted to Ton That Lê (Mr. Thuyet's younger brother) in July 1886 were almost gone. Moreover, the collection of military supplies, money, rice, and taxes for which General (Đề-đốc) Trần Xuân Soạn was responsible had also encountered many obstacles. The Resistance's activities grew ever less effective, while the leadership of the Resistance could find no way out.

On the night of the 14th going into the 15th of August 1886, a band of Righteous Army troops from Ha Tinh gathered at Nong Cong, led by Tu Tai Phong (Mr. Thuyet's brother), attacked the citadel of Thanh Hoa but were repelled by four companies of French naval infantry, although two French officers were killed and Pivert, the Residency Assistant (Tham-biện sứ-quán), was seriously wounded. (This account comes from Major Pelletier of Colonel Mignot's force.) On this same occasion, the Resistance posted a manifesto directly at the French Resident's Office (Tòa Khâm), insulting the invading band and their lackeys, including King Đồng Khánh and Nguyễn Hữu Độ. The French were furious and ordered the Privy Council to strike the name of Tôn Thất Thuyết and his entire family from the Tôn Thất register and change his surname to his mother's family name, Lê. (A royal decree under King Khải Định later restored Mr. Thuyet's former status in all respects.) From that time, people called the Resistance leader Lê Văn Thuyết.
"""

with open('/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch5-translated.txt', 'w', encoding='utf-8') as f:
    f.write(translation)

print(f"Translation written: {len(translation)} chars")
