#!/usr/bin/env python3
"""Write the initial section of the English translation to the output file."""
import subprocess, sys

output_path = "/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch9-translated.txt"

translation = """CHAPTER IX

FAMOUS BATTLES OF THE TRUNG KỲ RESISTANCE AGAINST THE FRENCH

1: THE BA ĐÌNH UPRISING
(1886 — 1887)

Through the various uprisings we have already examined, we now come to that era when the French openly set about seizing the remainder of Trung Kỳ, intending to settle accounts with the whole of Việt Nam. Few Vietnamese, and indeed few French colonists, have forgotten the famous battles recounted below.

These battles revealed to all ranks of our compatriots that Việt Nam, upon its path of struggle for survival — though it had often been defeated by the enemy — had also prevailed against a wealthy and vastly better-equipped foe. It may be said that Vietnamese history is an unceasing struggle on every front, so that our people might endure forever upon this S-shaped strip of land; the national spirit, built upon the two words "freedom" and "independence," is the root from which the Vietnamese draw all their strength, and from the ancestors to the descendants they cling to that root, preserving it with every capacity and every passion.

Because of this, the Vietnamese people — no matter how dark their condition, how desperate their situation — always return at once to composure and then rise up with such power that the enemy cannot imagine it. And often we defeat them with the simplest of means, which is itself an extraordinary thing. Only by witnessing such a resurgence does one understand that no force can annihilate the Vietnamese people, yesterday or today.

But which uprisings truly embodied this terrible resilience? The answer: the Hùng Lĩnh uprising of Tống Duy Tân, the Bãi Sậy uprising of Nguyễn Thiện Thuật, the Ba Đình uprising of Phạm Bành, Hoàng Bật Đạt, and Đinh Công Tráng, the Hương Khê uprising of Phan Đình Phùng, and the Yên Thế uprising of Hoàng Hoa Thám.

The Ba Đình uprising broke out at the time when Tôn Thất Thuyết issued the Cần Vương Edict, denouncing the imperialists' ambition to swallow our entire nation. Many scholar-gentry and local notables concentrated in Thanh Hóa Province, a region bordering both Trung Kỳ and Bắc Kỳ, with many high mountains and dense forests stretching from the Đà River to the South China Sea, cutting across National Route 1 between Ninh Bình and Thanh Hóa. This area was strategically formidable due to its natural terrain. It was also economically rich, abundant in talent, and the source of many degree-holders. The central aim of the resistance leaders here was to seize the strategic throat between Trung and Bắc Kỳ, cutting off and controlling the enemy's main communication artery — National Route 1 by land. The water route from the sea could facilitate supply for the insurgent army whenever needed, using sailing boats, and also served as their retreat route if driven from the Hùng Lĩnh mountains.

Beginning in September 1886, Ba Đình inscribed its name into history. Ba Đình comprised three villages — Mỹ Khê, Thượng Thọ, and Mậu Thịnh — in Thanh Hóa Province (the birthplace of the Lê and Nguyễn dynasties), bordering Ninh Bình Province between the Hoạt Giang and Đại Lai Rivers flowing through Nga Sơn District. In the rainy season, standing water surrounded Ba Đình, deep enough to submerge a man, making it rise like an island up to two thước above the water; in the dry season, rice fields encircled these three villages like a marsh before a wall of thick green bamboo. To approach Ba Đình, there was but a single path from the dike of the canal (the river connecting the Hoạt Giang and Đại Lai).

(1) To speak of the Ba Đình uprising is to speak of the resistance of the people of Thanh Hóa Province following the Cần Vương Edict.

The three villages shared one great communal house, and the entire complex was called Ba Đình.

To block the French advance and impede their encirclement and attack, the Resistance planted numerous stakes in the marshes and dug moats and built ramparts — fortifications that, in truth, had only temporary value against Western weaponry. Those entrusted with directing the resistance here were Đốc học Phạm Bành, Đề đốc Đinh Công Tráng, Đề đốc Nguyễn Khế, and two Mường chieftains, Hà Văn Mao and Cầm Bá Thước, among others. Tuần vũ Nguyễn Bột Nô of Tĩnh Gia, Tổng đốc Lê Như Rạng, Bố chánh Ngô Xuân Quỳnh, and Tri huyện Nông Cống Tôn Thất Hàm also enthusiastically responded.

Combat responsibilities were distributed as follows: military affairs were under the command of Đinh Công Tráng, a fearless soldier who governed his troops with strict discipline. The construction of fortifications was the task of Nguyễn Khế. French officers had to acknowledge that Nguyễn's fortifications were built in accordance with proper scientific methods, revealing considerable strategic knowledge and skill in exploiting natural advantages. Beyond Ba Đình itself, an outer defense line manned by militia had the purpose of harassing the enemy and preventing them from approaching our positions. This was commanded by Đề đốc Trần Xuân Soạn. Nevertheless, as we shall see, the main force remained concentrated at Ba Đình.

After the summer rice harvest (May 1886), when the fields were temporarily dry, the Resistance began constructing the Ba Đình fortifications. They provided funds for the evacuation of the elderly, women, and children from the three villages to neighboring settlements such as Liên, Nghị, and Vinh; only able-bodied men stayed behind to fight. Each village in the two districts of Nga Sơn and Tống Sơn was required to contribute thirty pig baskets, one hundred bamboo poles, ten loads of straw, and laborers to dig trenches around the three villages. The moats were four thước wide and three thước deep; the excavated earth was piled high to form a rampart. The rampart rose eight to ten thước, wide enough for troops to move along it for patrolling around Ba Đình. On the outer face of the rampart they planted spikes; every five thước a sharpened stake lay just below the water's surface. Beyond this was a dense bamboo palisade with thorny branches spread out to a width of fifty thước. Along the top of the rampart, thousands of pig baskets filled with mud were stacked high. From inside, looking through the gaps between baskets, one could see everything outside clearly; conversely, those outside could see nothing within. After completing this rampart (which took a month), they let river water flood the fields, and Ba Đình suddenly became a vast lake.

From early October 1886, many French supply columns traveling National Route 1 were ambushed in stages by gunfire from the forest, forcing the French to launch sweep-and-encircle operations. The commanders of the Nam Định and Thanh Hóa sectors at that time were Colonel Dodds and Colonel Metzinger. The blockade by these two French commanders began in December 1886, aiming to cut off communication and supply to the insurgent army at both the inner and outer defense lines of Ba Đình.

On 18 December 1886, French forces were seen operating at the first defense line. Artillery went ahead to clear the way; infantry followed, capturing several small villages. The insurgents fought back fiercely, inflicting heavy losses on the enemy.

Dodds's Nam Định column attacked from the north, achieving some initial success. Major Nugent, commanding the second Tonkinese battalion, captured an outpost at Thượng Thọ village, but then met stiff resistance from the forts behind, a few hundred thước further on, and had to halt before the second defense line. The enemy withdrew, having suffered many dead and wounded, including Lieutenant Audibert.

Metzinger's Thanh Hóa column attacked from the south and also took losses, despite considerable bravery. Lieutenant Zanner and Lieutenant Tuffier, commanding this column, had to advance through water up to their shoulders. Volleys of gunfire came from within. Zanner was shot in the head and killed instantly, beside many of his soldiers in the trenches. Tuffier did not falter; he urged his men forward, pistol in one hand and sword in the other. But in the end, he and his comrades were also wounded, forcing Major Blaise to order the 80mm heavy artillery to open intense fire so his men could retreat, while the insurgents rushed out in a fierce pursuit.

This attack was deemed a failure. The French were forced to resume their blockade strategy, but lacking sufficient troops they had to summon forces from elsewhere, including their navy stationed off the coast of China.

By early January 1887, the French had assembled enough troops to blockade Ba Đình: two infantry companies of 260 men under Majors Rambaud, Deixonne, and Cortes; a naval infantry company of 180 men under Major Valence; a company of the second Foreign Legion regiment of 200 men under Major Préfet; a company of the third African infantry battalion of 180 men under Major Bernard; and a landing company from the warship Turenne with 150 men under a naval lieutenant.

The enemy artillery was equally formidable: ten 81mm cannon served by 120 artillerymen; four 95mm cannon under Major Girard; four 65mm naval guns served by 30 sailors; two Hotchkiss guns with 15 men; and four additional cannon with 80 men.

Combat engineers were under Major Joffre and Lieutenant Netter, with 46 soldiers. Collaborator troops (lính khố xanh) numbered 1,950 under Majors Monniot, Nugent, Bouchage, Audry, Blaise, and Lieutenants Lambelin, Drujon, and Chatier. The total French force was 3,388 men, of whom 1,580 were French soldiers.

The navy had four gunboats supporting and supplying the operation: the gunboat Estoc under Lieutenant Thounine, the Bossant under Lieutenant Le Prieur, the Avalanche under Lieutenant Dantin, and the Moulin under Lieutenant Surcouf. The enemy also brought 5,000 coolies seized from Phát Diệm (Bắc Kỳ) to Ba Đình for battlefield service and supply. All these forces were under the command of Colonel Brissaud.

The plan for this final assault on Ba Đình was decisive. It relied on the engineers building ramparts along the dike to advance step by step; they also drained the tidal water, letting it recede, then blocked it from returning. On 6 January 1887, artillery opened fire in support of the infantry advance. The French divided into three columns; by two in the afternoon, all three had reached the fortifications on the dike.

The first column, led by Lieutenant Drujon and Fauret, reached within a hundred thước of our fortifications and encountered the bamboo palisade. They had to blast and chop their way through with mines and axes, while our men, concealed within, fired fiercely. Drujon shouted for his men to advance to the village gate, but halfway there both he and Fauret were hit by gunfire and forced to withdraw.

The second column — the center — under Major Bouchage, comprised Lieutenant Lambelin's group, a second Tonkinese battalion, and the fourth Tonkinese battalion under Major Goering. This column moved to the left of the first and, approaching within twenty thước of the fortifications, was also stopped by insurgent fire. Lambelin and two non-commissioned officers, along with many soldiers, were hit and fell back. Engineers and auxiliaries also took heavy casualties.

The third column, moving to the right under Lieutenant Collot, consisted of troops from the second Tonkinese battalion leading engineers with explosives, coolies carrying brushwood and baskets of earth, with the objective of breaching our defenses. These too were hit by crossfire and could not get near.

Colonel Dodds, seeing the situation was too difficult, sounded the retreat. But the center column had advanced too far and could not withdraw immediately. Artillery had to bombard to support this wing, and then the entire infantry and Goering's right-flank force had to make a desperate charge to provide cover. Goering was struck in the shoulder, and his troops became bogged down and unable to move. Major Bouchage, commanding this assault, was also wounded in the thigh as he urged the retreat and conveyed the wounded to the rear. Thanks to the heavy artillery, the assault force gradually pulled back. Major Amar of the second Tonkinese battalion, diligently overseeing the withdrawal, was also wounded.

The result of this battle: the enemy lost four officers and a large number of soldiers of various ranks. The insurgent tactic at that time was to lure the enemy close, exploit the positional advantage, and kill them. Each time an enemy commander fell, a voice from the watchtower would call for troops to go out and retrieve the enemy's corpse for a reward. From the experience of this battle, the French abandoned frontal assaults; meanwhile, from within the fortifications, our men would hurl challenges that drove the enemy to fury.

Colonel Brissaud realized that a direct assault was ineffective and recalled the siege of Puebla in Mexico. He mobilized the main force, dividing them into two elements: one to counter internal attacks, one for external sorties, and then maintained a prolonged siege. It must be noted that this strategy could work only because the outer force under Đề Soạn had sufficient strength merely to harass; if the insurgents had attacked from within while the outer force struck from without, the French, caught in the middle, could hardly have held out.

Brissaud then had communication trenches dug, advancing step by step toward Ba Đình fortress. Meanwhile, he collected timber, bamboo, and iron wire from various places, building them into continuous palisades with a fort every interval for day-time troop shelter; where the water was deep, he built forts on ironclad boats or rafts. Then he had cannon fire poured into Ba Đình day and night. This tactic proved effective; his engineers could advance without suffering heavy casualties as before. Then both columns assaulted again — the southern under Metzinger, the northern under Dodds. By 15 February 1887, the first French units were only about a hundred thước from our positions. Yet they still did not know our defensive layout, seeing only rows of sharp stakes rising from the water and estimating our defense line to be about 1,200 thước long and 400 thước wide. On occasion, the French captured some who had fled Ba Đình because they could no longer endure the destruction wrought by French artillery; only then did they learn of our defensive arrangements, which were focused on defense, holding a defensive posture because the enemy's firepower was indeed overwhelming. In the end, the inner and outer forces could not support each other; the insurgents held out only as long as they could, though their spirit remained unbroken.

On 19 January, the enemy's engineers advanced to the very edge of the fortifications. Concentrating into three columns, they used heavy artillery to open the way, then stormed the north side of Thượng Thọ village, using flamethrowers to burn the fortifications and camps within. The insurgents, sheltered behind bamboo-and-mud ramparts, fired back; by night they used the darkness to sally forth and kill the enemy. The French, sacrificing heavily, refused to retreat and redoubled their burning efforts. Grenades and explosives rained upon our positions — up to 16,000 shells, turning Ba Đình into a sea of fire. The enemy suffered heavy losses, but before such overwhelming firepower, we had no means to stop them.

A retreat through blood and fire: A few days earlier, Đinh Công Tráng had seen that Ba Đình's situation might become critical. He wrote to Đề Soạn at Quảng Hóa, requesting a strong external attack to divide the enemy's forces. Although Soạn then had 2,000 troops stationed about half a day's march from Ba Đình, he dared not advance close to the enemy's rear, only firing artillery in support from a distance, and thus could not restrain enemy operations against Ba Đình.

Đinh Công Tráng was forced to open a bloody path for his troops to withdraw at dusk, under the glow of fire that lit the sky. The insurgents charged out in coordination with friendly units from neighboring villages attacking inward. A thick fog descended; the two sides became intermingled, recognizing each other only by the flash of gunfire. The roar of explosions large and small rumbled across the sky. The battle was savage beyond description. At dawn the next day a ghastly scene met everyone's eyes: on the French defensive line, corpses lay strewn about, blood mixing with mud in a stench that made one retch. And the French who entered Ba Đình also encountered many unburied corpses, flies and maggots swarming. In the yard of the communal house lay the body of Đề đốc Khế — this was where the most ferocious fighting had occurred.

The French occupation of Ba Đình was hailed by the colonialists as a glorious feat of arms, earning Colonel Brissaud promotion to Brigadier-General. But according to documents captured by the French — a letter from Đinh Công Tráng to the insurgent commander at Mã Cao — our troops were forced to abandon Ba Đình hastily because thousands of French soldiers (including auxiliaries) had left their corpses around the fortifications; the water was stagnant, the dead unburied, and cholera threatened to break out. The transfer of forces to a second position was unavoidable. Thus we may conclude that, had it not been for this factor, the insurgents might have prolonged the campaign, and the French would not have won.

Some observations on the Ba Đình battle: If one thinks that the resistance leaders held fast at Ba Đình simply to fight it out with the French army, this would be an oversimplification. For although we had the advantage of terrain and natural features, our troops were few, our provisions and weapons limited, and we could hold this position for only a certain period, long or short. At this time the enemy held numerous political, economic, and military advantages; naturally their resources were abundant, their recruitment easy, and a prolonged campaign would inevitably bring them victory. We lacked external reinforcement, so our capacity for holding out was merely a matter of months. Phạm Bành, Đinh Công Tráng, and their comrades were not ignorant of this. Surely they intended only to use the Ba Đình battlefield, with its formidable position, to destroy a certain portion of the enemy's forces, then exploit the renown of this resistance for propaganda abroad and throughout the country.

According to Đinh Công Tráng's report, at 4:00 AM on 21 January 1887, he and Phạm Bành broke through the enemy's lines and escaped. The enemy suffered a large number of dead, while our side had approximately 150 killed and wounded.

The enemy had suffered quite heavily during the months-long blockade and assault on Ba Đình. In France, political circles in Paris were greatly agitated, and they concealed their defeats at the Ba Đình battle zone, ordering the expeditionary forces to complete the destruction of the Resistance here at any cost, permitting them to report only victory.

We also note that the fighting spirit at Ba Đình was highly commendable: from the very start of building this battle zone to turn it into a grave for the invaders, only the elderly, women, and children were evacuated; all able-bodied men remained behind, resolved to die fighting the enemy. Ammunition was scarce because supply was heavily obstructed by the enemy's ever-tightening net, so the Resistance had to economize every single bullet. They had to wait until the enemy came close to the fortifications, within certain range, before firing to be sure of hitting; thanks to this, every round fired took an enemy life in the stinking mire. The insurgents fought with extraordinary determination and courage, causing great hardship for the enemy from officers to men. After a time, Brissaud fell ill from exhaustion and his inability to adapt to the watery terrain. Major J. Masson, in his book "Souvenir de l'Annam et du Tonkin," recorded the desperation of the expeditionary force thus:

"Our situation before Ba Đình had reached such a point that we could no more count on an enemy surrender than on their generosity should we be defeated."

After breaking this position — the great achievement of the people of Nga Sơn and Tống Sơn districts — the French and the Nam Triều feudal authorities expunged the three villages of Thượng Thọ, Mậu Thịnh, and Mỹ Khê from the map of Thanh Hóa Province and erected a plaque there, with menacing words for the people:

"These three villages — Mỹ Khê, Thượng Thọ, and Mậu Thịnh — have been condemned as bandits and rebels for having built walls and ramparts at this place without notifying the authorities. These villages shall henceforth vanish from the face of the earth. Those who transgress shall be punished..."

But these three villages, together with the people of Ba Đình, Tống Sơn, and Nga Sơn, have not "vanished" from memory or from the modern history of our country. On the contrary, there is no Vietnamese who does not remember that Ba Đình was one of the most glorious battlegrounds of the beloved sons of the Vietnamese Fatherland, and the burial ground of countless imperialist officers and soldiers sacrificed by French capitalists and financiers to their work of invasion and plunder.

The final phase of the Ba Đình insurgents — Mã Cao was a secondary position for resisting the French, supporting Ba Đình when the insurgents used Ba Đình as a site to apply the strategy of attrition. Mã Cao was built by a number of scholar-gentry from various places, and the leader of this battle zone was the Mường chieftain Hà Văn Mao. In the Mã Cao force there were also some "Black Flag" soldiers. This position was covered by dense forests and high mountains, with paths through the mountains to Laos and Yunnan. Additionally, numerous river branches flowed from the sea via National Route 1, such as the Lèn, Mã, and Chu Rivers, crossing the plains to the highlands of Thanh Hóa Province and even up to Ninh Bình, running parallel to the road to Bắc Kỳ.

The Resistance built a central artillery fort right at a bend in the river, where the water was fifteen thước deep and forty thước wide, using the river itself as a moat. In the riverbed, rocks jutted up unevenly. At the river mouth, a dike built by the locals for flood control; our troops dug a trench along the dike. To protect the central artillery fort, six smaller forts were placed within a three-square-kilometer radius, nestled in the thickets, built of earth that was tamped hard when dry so that rifle bullets could not penetrate. One of these forts housed a gunpowder workshop. The adjacent dense forest, called Cụ Bảo Forest, was crisscrossed with trenches to block enemy attacks from outside.

(1) Captain Joffre, later to become Marshal of France, renowned in the First World War, was seriously wounded during the French assault on Ba Đình.

From Ba Đình, the insurgents withdrew to Mã Cao, and the enemy pursued at once. They divided into two columns, each for pursuit: Colonel Dodds advanced into Quảng Hóa District, while Colonel Metzinger followed the right bank of the Mã River toward Thọ District. They arranged to meet at Mã Cao. Besides these two combat columns, a third under Major Joffre was responsible for commandeering all local boats for the transport of food and ammunition.

At noon on 22 February 1887, both columns arrived at their rendezvous. They had not yet learned the situation at Mã Cao when a reactionary district magistrate seized two locals to guide the enemy, suspecting they were Mã Cao's men. And indeed they were Resistance fighters, for which the collaborators could find no proof. They planned to lead the French astray into an ambush, but the wily enemy refused, demanding to go directly to the Mã Cao position. Upon reaching a deep valley, crossing a stream, a cannon shot and a volley of rifle fire came from the far bank. Brissaud immediately ordered a swift retreat to avoid encirclement, then divided his forces into three groups to attack from three sides, both to reconnoiter the routes and to check the Resistance attack. Dodds swung right, Metzinger left, Diguet held the center, while Major Nugent and two lieutenants, Faure and Betzelère, commanded mobile units.

Our guns crashed from all sides; the enemy could not tell where we were strong or weak. Brissaud ordered the center column to advance, ford the river to seize a small fort blocking the path, while the vanguard pressed into the thick forest, and the other units sought ways to avoid our encirclement.

After an hour of searching, the French vanguard stopped before a deep valley surrounded by dense trees. The French right wing came under fire at very close range — only a few thước away; from thirty thước across the valley, insurgent bullets also whistled past. The two guides bolted, calling to the insurgents, reporting that a French general and his staff had arrived. Unluckily for these two, they were pursued and shot dead by auxiliary troops.

The French assault force continued advancing, with land and water units maintaining communication, giving them strength. The insurgents had to fall back within their defense line to exploit other positions. Drums and bugles called upon the auxiliaries to turn their guns on the enemy, mingling with the sounds of small and large arms that echoed across the forested mountains. The French used mortars to fire at areas where ambushes seemed to lie and where gun smoke rose. From the forts hidden in the valley thickets, the insurgents concentrated fire on the French units before them. The enemy faltered; the bitter battle continued until evening. In the end, the insurgents, fearing the enemy's superior numbers would encircle them and cut off their retreat, withdrew into the valley. By nightfall, the enemy from the north managed to penetrate the central fort; the insurgents retreated southward. But the enemy paid a heavy price for this capture: many soldiers dead; a navy lieutenant was shot through the chest and died on the spot as he rushed into the fort; Lieutenant Causé of the second Tonkinese battalion was also wounded, along with many indigenous soldiers. The French prepared to attack the remaining forts the next day, but the insurgents had already slipped away that very night. Here too, the French acknowledged that the insurgents' defensive works were as methodically designed as at Ba Đình, and that if we had had greater offensive capability — if not for our few troops and meager weapons and ammunition — the outcome might have been different.

The uprising of the scholar-gentry and people of Thanh Hóa then gradually receded into the past. From that point onward, the insurgents no longer established themselves in any single position, for they had only enough strength for guerrilla warfare, and the resistance shifted to the highlands rather than remaining on the plains.

And the final fates of the Cần Vương leaders?

When he withdrew from Ba Đình on the night of 21 January 1887, Phạm Bành fled to Mã Cao. Some collaborators urged the French to capture his mother and children to force him to surrender. Indeed, he surrendered to save his mother, but once his mother and children were freed, he took his own life that very day. Nowadays, people consider that in times of national crisis one should place loyalty to country before filial piety. Was Phạm Bành's conception of loyalty and filial duty misplaced?

As for Đinh Công Tráng? After the Mã Cao defensive force collapsed, Tráng tried to gather the remnants to reorganize resistance in the neighboring regions, but the French were searching too intensely. He had to flee to Nghệ An.

On 5 October 1887, the village chief of Tăng Yên denounced him to Major Coste, commander of the Đô Lương garrison on the Cả River. Coste and a Lieutenant De Fitz Jammes immediately took 65 soldiers upriver by boat the very night they received this information. Tăng Yên village was about twenty kilometers from the river, the road very difficult due to prolonged rain. At three in the morning they arrived; the village was still silent as a tomb. They rushed the stilt-house where Tráng was staying; he knew only when it was too late. From inside, he fired, killing two enemy soldiers, but Coste and a soldier named Nguyễn Tuyên still burst in, firing multiple revolver shots. Tráng and his brother-in-law were killed. (Some sources record that after the Ba Đình battle, Tráng withdrew to Ngọc Lạc, and on the road to Tương Dương District in Nghệ An, he encountered a French patrol; he fought desperately, was captured, and committed suicide.)

The French praised Đinh Công Tráng: "He never avoided danger, always leading from the front on every operation. Yet he was cautious and bold, and possessed an ardent patriotism. Though a commoner, he had many noble qualities; he stood at the head of a number of officials, most of whom were proud-spirited. If he had been supported by capable men, the French would have struggled long and hard, and who knows how they might have triumphed..."

These were the words of Colonel Masson, who participated in commanding the battles at Ba Đình and later praised Đinh Công Tráng warmly, calling him "a man of order, courage, strict military discipline, keen observation, and patience. Moreover, he understood both himself and others, and never employed his troops wastefully. He was a strategist to be admired, skilled at deploying forces and luring the enemy into dangerous positions."

Ba Đình and Mã Cao were suppressed, but the colonialists could not yet set aside their arms to eat and sleep in peace. Their troops had to hastily take to the road again, to clash with other patriotic forces even more formidable — the Hùng Lĩnh and Hương Khê uprisings, and the campaign of Lê Ninh from 1885 onward."""

# Encode as base64 to avoid shell escaping issues
import base64
encoded = base64.b64encode(translation.encode('utf-8')).decode('ascii')

cmd = f"echo '{encoded}' | base64 -d > {output_path}"
result = subprocess.run(
    ["ssh", "local-machine", cmd],
    capture_output=True, text=True, timeout=30
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)
print("Exit:", result.returncode)

# Verify
result2 = subprocess.run(
    ["ssh", "local-machine", f"wc -l -c {output_path} && head -5 {output_path}"],
    capture_output=True, text=True, timeout=15
)
print(result2.stdout)
