#!/usr/bin/env python3
"""Append Section 3: Hùng Lĩnh Uprising translation."""
import subprocess, base64

output_path = "/home/vthen/work/post-colonial-vietnam/sources/vstb/translations/ch9-translated.txt"

section = """


2: THE HÙNG LĨNH UPRISING
(1886 — 1892)

Leading the uprising here (Hùng Lĩnh in Thanh Hóa) was Tống Duy Tân, a scholar-official who had once served as Sơn phòng sứ (Mountain Defense Commissioner) in this very region. His native village was Đông Biên (Bồng Trung) in Vĩnh Lộc District, Thanh Hóa Province. He earned the Cử nhân degree at thirty-six and the Tiến sĩ degree three years later, under the reign of Tự Đức. At forty-one he was appointed Đốc học (Education Commissioner) of Thanh Hóa Province, and four years later he was transferred to the post of Thương biện tỉnh vụ (Provincial Affairs Assistant) of Thanh Hóa. His final position was Chánh sứ Sơn phòng (Chief Mountain Defense Commissioner) for Vĩnh Lộc. His uprising occurred at the same time as many others — Ba Đình, Bãi Sậy, Mã Cao — during the period when the anti-French movement was spreading throughout Trung and Bắc Kỳ.

Tống Duy Tân's organization consisted of local militia: each district supplied one cơ (about 200 men), led by a Cơ trưởng. His tactics were essentially identical to those of the Ba Đình leaders: on principle, he selected a strategically formidable position, built solid fortifications, and then lured the enemy forward. When the enemy proved too strong, the insurgents would withdraw to another location. (This defensive strategy had the weakness that the enemy possessed artillery, making it impossible for the insurgents to preserve their main force.) Assisting Tống Duy Tân were the Mường chieftains Cầm Bá Thước and Cao Điền, who were then raising troops at Sầm Sơn.

During the period of fighting against French forces under Major Térillon at Đông Khố commune, Tống's insurgents once defeated the French, killing many of them. Later, Tống was subjected to a fierce French attack and had to flee to Bắc Kỳ and then to China. In November 1888, Emperor Hàm Nghi was captured and exiled. Tống received orders from Tôn Thất Thuyết to return to Thanh Hóa to resume operations. At the beginning of 1889, he established a base at Vận Động in western Thanh Hóa, about twenty kilometers northwest of Nông Cống. He dug moats and built ramparts, intending to make this a long-term base. Thanks to the Mường chieftain Cầm's support, many Mường compatriots in the region enthusiastically joined the insurgent army.

On 8 October 1889, receiving word that Tống Duy Tân's insurgents were active at Vận Động, Lieutenant Morfond, commander of the indigenous auxiliary garrison at Nông Cống, took four French soldiers and twenty Vietnamese auxiliaries to reconnoiter. Approaching Vận Động, they ran into the insurgents' fortifications. From behind the ramparts, insurgent bullets rained down like rain, killing Morfond, four French soldiers, and four auxiliaries on the spot. Most of the remaining fled, and several more died. Three days later, a force of 180 enemy soldiers marched in from Thanh Hóa town. After this second engagement, the French lost another dozen men. On 22 October, Colonel Barberet led 185 French soldiers from Thanh Hóa, only to find that the insurgents had already withdrawn to Đa Bút, an even more formidable position. To reach it, one could only take small paths. Before advancing, the enemy bombarded with artillery. The two sides fought fiercely from 2 to 3 November, after which the insurgents moved north to Phố Cát. The enemy pursued but gained nothing and had to return to Thanh Hóa on 9 November. At the end of this month, a notable event: Đề Soạn's forces came to cooperate with Tống's and Cao's troops. The Hùng Lĩnh insurgents grew stronger and expanded their operations across Yên Định District.

The colonialists began to worry and saw the need to suppress the Hùng Lĩnh movement to limit its influence on other regions. Lieutenant-Colonel Lefèvre replaced Barberet. He brought along a cavalry unit with 80mm mortars. The insurgents were then at Vạn Lại, thirty kilometers west of the provincial seat.

On 30 November 1889, the enemy reached Vạn Lại but did not open fire immediately. They investigated every aspect of the situation before striking. After the first engagement, the French were at a disadvantage: Colonel Lefèvre was severely wounded, and a number of French soldiers died. Lieutenant Colleta took command and, with Lefèvre's wounds bandaged, led the force back toward the provincial seat. Colleta withdrew to Yên Lược, south of Vạn Lại. Seizing the momentum, the insurgents divided into four groups and, armed with spears and pikes, attacked the enemy at close quarters for over two hours on the night of 1 December 1889, only withdrawing near dawn after setting Yên Lược ablaze.

The enemy suffered heavy losses and could no longer afford to underestimate us. This time they deployed 500 troops and two cannon, placing Lieutenant-Colonel Jorne de Lacale in command. Tống again changed position, for the enemy was far more numerous and powerful, and they had also discovered his whereabouts. The French pursued but without result. On 12 December, they marched back to Yên Lược to block the insurgents' route to the plains.

For five consecutive days from 20 December, the enemy conducted sweeps and searches of suspicious villages. On 30 December, they arrived at Sè village on information that insurgents were there; at noon on 1 January 1890, they encountered the insurgents at Kẽm village — an outpost with 400 soldiers and 140 riflemen sheltered behind fortifications. French cannon fired continuously for forty-five minutes, breaching the defenses, and then the French stormed in. Both sides fought fiercely; in the end, a French captain named Christophe and many soldiers perished. The insurgents withdrew at nightfall.

On the night of 5-6 March 1890, the insurgents raided Nông Cống in two columns: one attacked the district seat, while the other destroyed a bridge near the garrison to block enemy reinforcements. The insurgents also spread word that they would annihilate the Nông Cống garrison the following night. The garrison commander, Lieutenant Jolly, urgently sent word to the provincial capital. French Resident Lebrun hastily dispatched Lieutenants Savereux, Détienne, Miche, and Rémy with reinforcements, but they found nothing when they arrived. On the way back, an informant told them that 200 insurgents were present in a neighboring village; they sent a messenger back to the province for more troops. Our forces captured this messenger and, thanks to this, laid an ambush. Resident Lebrun led his troops in and was surrounded, beaten back to Nông Cống with considerable losses. Jolly's relief attempt was ineffective. When the news reached Thanh Hóa, Vice-Resident Neuville brought another 100 French troops, intending to coordinate an attack on the insurgents, but Lebrun had already been defeated and had retreated to Nông Cống. The insurgents, after their victory, moved on to Yên Lãng in Thọ Xuân District. The commander of this battle was Cao Điền.

On 29 March 1890, the French divided into two columns — one from Nông Cống, one from Thanh Hóa — totaling 200 soldiers with two artillery sections, and surrounded Yên Lãng. The insurgents were at a disadvantage in this battle, losing several men, including the Chánh tổng (cantonal chief) of Yên Lãng. On 16 April, Cao Điền's outpost at Na Lung was attacked. The insurgents lost five men and six rifles before moving to Thanh Khoải village. There Cao had about 400 men, 160 rifles, and two fortification guns. On 29 April, the two sides met at Mỹ Hòa, fought briefly, and then the insurgents withdrew to their main fort. Three enemy columns under officers Viola, Bonnet, and Marlier attacked the fort's front; two more under Le Breton and Détienne attacked the flanks; Lameray commanded the blocking force to cut off the insurgents' retreat. Despite the enemy's numbers and tight encirclement, they were decisively defeated. Several were killed (including Lieutenant Bonnet), several wounded (including Viola, shot in the right cheek), and six indigenous soldiers died. The main fort's position was a high hill surrounded by dense spikes. The enemy tried to cross and suffered heavily for their audacity. The battle lasted from 3 PM to 7 PM. After the victory, Cao Điền led his troops to Cửa Đại.

Months later (October 1890), 225 enemy troops attacked this position but failed; the insurgents moved on to An Lâm.

On 21 February 1891, Tống Duy Tân and Cao Điền both arrived at Lang Vinh, using the high mountains there for defense. Lieutenant Soler, Lieutenants Henschell, Marlier, and Normand came in search of them. Not knowing the routes, they forced the Lang Vinh village chief to guide them. At sixty thước from the position, insurgents fired from the thick underbrush. The French could not advance, and the next day, as they crossed a small stream, several were killed. But from February to April, the insurgents suffered a series of defeats, losing men and weapons. From April 1892 onward, the insurgent force numbered no more than 100 men and 50 rifles. The two leaders, Tống and Cao, fled yet again, this time to China, but they were no longer as optimistic as in previous years, because the people were too brutally terrorized to provide full support. The two leaders disbanded their battle units, sending them home to their villages to earn a living, keeping only a small number of volunteers who would follow them to the end.

From 24 September 1892, Thanh Hóa Resident Boulloche dispatched a patrol carrying Nguyệt, the son of Cai Mậu (a former insurgent commander), and his uncle Trương Lương, as guides. Boulloche arrived at the home of a local Thổ ty (indigenous chief) who had long participated in the righteous cause and had recently sheltered Cao Điền's men. Before the enemy arrived, the Thổ ty had already sent people to take Cao Điền into hiding at Đốc Tống's house in Lang Chánh.

Boulloche threatened the Thổ ty. His wife, terrified, guided Lieutenant Henschell and twenty soldiers to arrest Tống Duy Tân at 6 PM on 4 October 1892. The route was extremely perilous — climbing waterfalls and traversing ravines — and at 6 AM the next day they reached Tống's hiding place: a cave two kilometers long on a mountainside south of Niên Kỷ. Before the cave entrance stood a cannon and a burning fire. Tống was captured by surprise and taken to Thanh Hóa. (According to another source, after his defeat, Tống Duy Tân fled into the Sơn Dương forest of Thanh Hóa, where he was betrayed by a former student named Cao Ngọc Lễ in the pay of the French. This wretch, after having Tống decapitated and his head displayed, was granted the position of Tri huyện, later becoming Án sát. To curry favor, he would hunt down many more revolutionaries, like Nguyễn Thân and Hoàng Cao Khải who originated from Quảng Nam and Hà Tĩnh. The age produced such lines as:

"Vô địa khả mai Cao Ngọc Lễ,
Hữu thiên ưng thục Tống Duy Tân."
(No ground to bury Cao Ngọc Lễ,
Heaven itself should ripen Tống Duy Tân.)

Boulloche also had Cao Điền hunted on 3 October, a day earlier. On the way, his 30-man patrol was fiercely attacked; two insurgents were captured, six killed. Along with Cao Điền, only four or five men and two rifles remained. Cao escaped north and joined the Yên Thế insurgents, but was eventually caught in the enemy's net on 16 January 1896.

Now, reflecting upon this: while Ba Đình was active, the Hùng Lĩnh insurgents were also a thorn in the colonial forces' side, because each served as a diversion for the other. When Ba Đình fell, the Cần Vương army under Tống Duy Tân became isolated (1887), and its future was dark from that moment onward.

For six full years, Tống Duy Tân used guerrilla tactics to harass the enemy, raiding French outposts scattered along communication routes and in various districts and prefectures. After each battle, the insurgents would swiftly withdraw to the forested mountains to hold strong positions. However, on certain opportune occasions, the insurgents did mount some fairly large-scale mobile or encounter battles that the French still record: 8-22 October 1889, the Đa Bút battle on 2 November 1889, the Vạn Lại battle on 30 November 1889, the Yên Lược battle on 1 December 1889, the Nông Cống battle on 7 March 1890, the Mỹ Hòa battle on 29 April 1890, and so forth — these battles continued in sequence over six consecutive years. But the insurgents' strength eroded daily; replacements came slowly; the enemy, though suffering heavy losses, received steady supplies and always had formidable forces for suppression. The insurgents gradually disintegrated, and by early 1892, Tống Duy Tân saw that he could no longer preserve his forces. Forced to disband the soldiers who had followed him so long, he wept as he let them go. After this disbandment, both Tống and Cao fell into the enemy's net — truly a grievous and lamentable end.

Nevertheless, through Tống Duy Tân's activities, we see that his uprising clearly achieved a broad unity across all strata of the nation. The proclamations and leaflets calling upon the auxiliaries, drafted by Cao Điền, bore the reign-title Hàm Nghi thứ VI and raised the slogans: fight the enemy, seize the enemy's guns to arm the insurgents, Catholics and non-Catholics are one family, do not kill each other. In the early years, the insurgents fought with great spirit; many able-bodied men volunteered as local militia, so that the insurgents established a cơ in each prefecture and district, each commanded by a Cơ trưởng who was a Cần Vương adherent. During this period, the Mường compatriots also closed ranks with the Kinh people, driven and encouraged by chieftain Cầm Bá Thước.

(It should be noted that the uprising in Hà Tĩnh was first begun by Ấm Ninh, also known as Lê Ninh, styled Mạnh Khang. Ấm Ninh belonged to a line of hereditary officials in the region (Trung Lễ village, Văn Lâm canton, La Sơn District, Đức Thọ Prefecture, Hà Tĩnh Province). He contributed his own family wealth to recruit soldiers and forge weapons. His troops were drawn from the local area: from each household with three adult males, he took two; from those with two, he took one. He also recruited from his wife's home villages in Phù Long and Yên Trường communes of Nghệ An Province. His soldiers wore black uniforms with greenish-blue belts. Here he recruited five vệ (regiments) and concentrated them at Trung Lễ, combining with the insurgents of Tổng Nga canton, Kỳ Anh District, Thanh Hà Prefecture, for a total of five đạo (divisions).

Ấm Ninh was still young but possessed the blood of a hero, appearing at the very beginning of the Cần Vương movement. In Hà Tĩnh at that time, the Bố chánh (Provincial Commissioner) Lê Đại refused to obey the Cần Vương Edict, so Ấm Ninh marched his forces to the provincial seat, captured the collaborationist official, and killed him. After this event, his influence resounded everywhere. He established his headquarters at his home village, with his soldiers stationed throughout the La Giang region. He made contact with Emperor Hàm Nghi and was appointed Bang biện quân vụ (Assistant Military Commissioner). Later, Emperor Hàm Nghi ordered him to cooperate with Phan Đình Phùng in the Hương Khê Nghĩa Hội.)"""

encoded = base64.b64encode(section.encode('utf-8')).decode('ascii')
cmd = f"echo '{encoded}' | base64 -d >> {output_path}"
result = subprocess.run(
    ["ssh", "local-machine", cmd],
    capture_output=True, text=True, timeout=30
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)
print("Exit:", result.returncode)

result2 = subprocess.run(
    ["ssh", "local-machine", f"wc -l -c {output_path}"],
    capture_output=True, text=True, timeout=15
)
print(result2.stdout)
